import os
import shutil

def create_custom_language_prompt_file(custom_language_name):
    """Create a new prompt file for a custom language by copying en.json"""
    prompts_dir = os.path.join("config", "prompts")
    source_file = os.path.join(prompts_dir, "en.json")
    target_file = os.path.join(prompts_dir, f"{custom_language_name}.json")
    
    try:
        # Ensure the prompts directory exists
        os.makedirs(prompts_dir, exist_ok=True)
        
        # Copy en.json to the new custom language file
        if os.path.exists(source_file):
            shutil.copy2(source_file, target_file)
            return True, f"Created prompt file for {custom_language_name}"
        else:
            return False, "Source file en.json not found"
    except Exception as e:
        return False, f"Error creating prompt file: {str(e)}"

def add_custom_language(custom_language_name):
    """Add a custom language to the system"""
    if not custom_language_name or custom_language_name.strip() == "":
        return False, "Language name cannot be empty"
    
    custom_language_name = custom_language_name.strip()
    
    # Create the prompt file
    success, message = create_custom_language_prompt_file(custom_language_name)
    
    if success:
        return True, f"Custom language '{custom_language_name}' added successfully"
    else:
        return False, message


def get_available_languages():
    """Read language files from config/prompts directory and return display names"""
    prompts_dir = os.path.join("config", "prompts")
    available_languages = []
    
    if os.path.exists(prompts_dir):
        # Get all .json files in the prompts directory
        for filename in os.listdir(prompts_dir):
            if filename.endswith(".json"):
                # Get language code without extension
                lang_code = os.path.splitext(filename)[0]
                
                # Find the display name from LANGUAGE_MAP
                display_name_found = False
                for display_name, code in LANGUAGE_MAP.items():
                    if code == lang_code:
                        available_languages.append(display_name)
                        display_name_found = True
                        break
                
                # If language code not found in LANGUAGE_MAP, add it directly
                if not display_name_found:
                    available_languages.append(lang_code)  # Changed from lang_code.upper()
    
    # If no languages found, return default list
    if not available_languages:
        available_languages = [
            "English", "中文", "繁體中文", "日本語", "Español", 
            "Français", "Deutsch", "Italiano", "Português", 
            "Русский", "한국어", "ภาษาไทย", "Tiếng Việt"
        ]
    
    return sorted(set(available_languages))

def get_language_code(display_name):
    """Get language code from display name, supporting custom languages"""
    # First check if it's in the existing LANGUAGE_MAP
    if display_name in LANGUAGE_MAP:
        return LANGUAGE_MAP[display_name]
    
    # If not found, assume the display name is the language code in uppercase
    # Convert it to lowercase to match file naming convention
    return display_name.lower()

LANGUAGE_MAP = {
    "日本語": "ja",
    "中文": "zh",
    "繁體中文": "zh-Hant",
    "English": "en",
    "Español": "es",
    "Français": "fr",
    "Deutsch": "de",
    "Italiano": "it",
    "Português": "pt",
    "Русский": "ru",
    "한국어": "ko",
    "ภาษาไทย": "th",
    "Tiếng Việt": "vi"
}

LABEL_TRANSLATIONS = {
    # English
    "en": {
        "Source Language": "Source Language",
        "Target Language": "Target Language",
        "Use Online Model": "Use Online Model",
        "Models": "Models",
        "API Key": "API Key",
        "Remember Key": "Remember Key",
        "Enter your API key here": "Enter your API key here",
        "Upload File": "Upload Office File (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "Upload Files (.docx, .pptx, .xlsx, .pdf, .srt)",
        "Download Translated File": "Download Translated File",
        "Status Message": "Status Message",
        "Translate": "Translate",
        "Local Network Mode (Restart to Apply)": "Local Network Mode (Restart to Apply)",
        "Max Retries": "Max Retries",
        "Excel Mode": "Missing Translation? Try Mode 2",
        "Word Bilingual": "Enable Bilingual Comparison",
        "Excel Bilingual": "Enable Excel Bilingual Mode",
        "PDF Bilingual": "Enable PDF Bilingual Mode",
        "Continue Translation": "Continue Translation",
        "Thread Count": "Thread Count",
        "Stop Translation": "Stop Translation",
        "Stopping": "Stopping...",
        "Glossary": "Glossary",
        "Add Glossary": "+ Add Glossary...",
        "Drop CSV file here": "Drop CSV file here or click to browse",
        "Add Custom Language": "+ Add Custom...",
        "New Language Name": "New language name",
        "Language Name Placeholder": "e.g. Klingon",
        "Create Language": "Create",
        # Status messages
        "Extracting text": "Extracting text",
        "Removing duplicates": "Removing duplicates",
        "Splitting text": "Splitting text",
        "Translating content": "Translating content",
        "Translating": "Translating",
        "Checking results": "Checking results",
        "Restoring structure": "Restoring structure",
        "Generating output": "Generating output",
        "Extracting PDF content": "Extracting PDF content",
        "Generating translated PDF": "Generating translated PDF",
        "Translation completed": "Translation completed",
        "Total tokens used": "Total tokens used",
        "Preparing content": "Preparing content",
        "Continuing from": "Continuing from",
        "Retry": "Retry",
        "Show API Key": "Show API Key",
        "Hide API Key": "Hide API Key",
        "Security Tips": "Security Tips",
        "Security Tips Content": "This feature is only available in non-LAN mode. API keys are private data with security risks. Please enable with caution.",
        # Translation History
        "Translation History": "Translation History",
        "Refresh Records": "Refresh",
        "Back": "Back",
        "No translation records": "No translation records",
        "Time": "Time",
        "Duration": "Duration",
        "Online": "Online",
        "Offline": "Offline",
        "Open Output Folder": "Open Output Folder",
        "Open Log Folder": "Open Log Folder",
        "Status": "Status",
        "Success": "Success",
        "Failed": "Failed",
        "Stopped": "Stopped",
        "Tokens": "Tokens"
    },
    # Simplified Chinese
    "zh": {
        "Source Language": "源语言",
        "Target Language": "目标语言",
        "Use Online Model": "使用在线模型",
        "Models": "模型",
        "API Key": "API 密钥",
        "Remember Key": "记住密钥",
        "Enter your API key here": "在此输入您的 API 密钥",
        "Upload File": "上传文件 (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "上传文件 (.docx, .pptx, .xlsx, .pdf, .srt)",
        "Download Translated File": "下载翻译文件",
        "Status Message": "状态消息",
        "Translate": "翻译",
        "Local Network Mode (Restart to Apply)": "局域网模式（重启后生效）",
        "Max Retries": "最大重试次数",
        "Excel Mode": "有漏翻？尝试模式2",
        "Word Bilingual": "启用双语对照",
        "Excel Bilingual": "Excel 双语模式",
        "PDF Bilingual": "PDF 双语模式",
        "Continue Translation": "继续翻译",
        "Thread Count": "线程数量",
        "Stop Translation": "停止翻译",
        "Stopping": "正在停止...",
        "Glossary": "词汇表",
        "Add Glossary": "+ 添加词汇表...",
        "Drop CSV file here": "拖放CSV文件或点击浏览",
        "Add Custom Language": "+ 添加自定义语言...",
        "New Language Name": "新语言名称",
        "Language Name Placeholder": "例如：克林贡语",
        "Create Language": "创建",
        # Status messages
        "Extracting text": "正在提取文本",
        "Removing duplicates": "正在去除重复",
        "Splitting text": "正在拆分文本",
        "Translating content": "正在翻译内容",
        "Translating": "翻译中",
        "Checking results": "正在检查结果",
        "Restoring structure": "正在恢复结构",
        "Generating output": "正在生成输出",
        "Extracting PDF content": "正在提取PDF内容",
        "Generating translated PDF": "正在生成翻译后的PDF文件",
        "Translation completed": "翻译完成",
        "Total tokens used": "本次共消耗tokens",
        "Preparing content": "正在准备内容",
        "Continuing from": "继续自",
        "Retry": "重试",
        "Show API Key": "显示密钥",
        "Hide API Key": "隐藏密钥",
        "Security Tips": "安全提示",
        "Security Tips Content": "此功能仅在非局域网模式下可用。密钥为个人隐私数据，存在安全风险，请确认后谨慎开启。",
        # Translation History
        "Translation History": "翻译记录",
        "Refresh Records": "刷新",
        "Back": "返回",
        "No translation records": "暂无翻译记录",
        "Time": "时间",
        "Duration": "耗时",
        "Online": "在线",
        "Offline": "离线",
        "Open Output Folder": "打开输出文件夹",
        "Open Log Folder": "打开日志文件夹",
        "Status": "状态",
        "Success": "成功",
        "Failed": "失败",
        "Stopped": "已停止",
        "Tokens": "Tokens"
    },
    # Traditional Chinese
    "zh-Hant": {
        "Source Language": "來源語言",
        "Target Language": "目標語言",
        "Use Online Model": "使用線上模型",
        "Models": "模型",
        "API Key": "API 金鑰",
        "Remember Key": "記住金鑰",
        "Enter your API key here": "在此輸入您的 API 金鑰",
        "Upload File": "上傳檔案 (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "上傳檔案 (.docx, .pptx, .xlsx, .pdf, .srt)",
        "Download Translated File": "下載翻譯後的檔案",
        "Status Message": "狀態訊息",
        "Translate": "翻譯",
        "Local Network Mode (Restart to Apply)": "區域網路模式（重新啟動後生效）",
        "Max Retries": "最大重試次數",
        "Excel Mode": "有漏翻？嘗試模式2",
        "Word Bilingual": "啟用雙語對照",
        "Excel Bilingual": "Excel 雙語模式",
        "PDF Bilingual": "PDF 雙語模式",
        "Continue Translation": "繼續翻譯",
        "Thread Count": "執行緒數量",
        "Stop Translation": "停止翻譯",
        "Stopping": "正在停止...",
        "Glossary": "詞彙表",
        "Add Glossary": "+ 新增詞彙表...",
        "Drop CSV file here": "拖放CSV檔案或點擊瀏覽",
        "Add Custom Language": "+ 新增自訂語言...",
        "New Language Name": "新語言名稱",
        "Language Name Placeholder": "例如：克林貢語",
        "Create Language": "建立",
        # Status messages
        "Extracting text": "正在擷取文字",
        "Removing duplicates": "正在移除重複",
        "Splitting text": "正在拆分文字",
        "Translating content": "正在翻譯內容",
        "Translating": "翻譯中",
        "Checking results": "正在檢查結果",
        "Restoring structure": "正在還原結構",
        "Generating output": "正在產生輸出",
        "Extracting PDF content": "正在提取PDF內容",
        "Generating translated PDF": "正在產生翻譯後的PDF檔案",
        "Translation completed": "翻譯完成",
        "Total tokens used": "本次共消耗tokens",
        "Preparing content": "正在準備內容",
        "Continuing from": "繼續自",
        "Retry": "重試",
        "Security Tips": "安全提示",
        "Security Tips Content": "此功能僅在非區域網路模式下可用。金鑰為個人隱私資料，存在安全風險，請確認後謹慎開啟。",
        "Show API Key": "顯示金鑰",
        "Hide API Key": "隱藏金鑰",
        # Translation History
        "Translation History": "翻譯記錄",
        "Refresh Records": "重新整理",
        "Back": "返回",
        "No translation records": "暫無翻譯記錄",
        "Time": "時間",
        "Duration": "耗時",
        "Online": "線上",
        "Offline": "離線",
        "Open Output Folder": "開啟輸出資料夾",
        "Open Log Folder": "開啟日誌資料夾",
        "Status": "狀態",
        "Success": "成功",
        "Failed": "失敗",
        "Stopped": "已停止",
        "Tokens": "Tokens"
    },
    # Japanese
    "ja": {
        "Source Language": "ソース言語",
        "Target Language": "ターゲット言語",
        "Use Online Model": "オンラインモデルを使用",
        "Models": "モデル",
        "API Key": "APIキー",
        "Remember Key": "キーを記憶",
        "Enter your API key here": "APIキーを入力してください",
        "Upload File": "ファイルをアップロード (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "ファイルをアップロード (.docx, .pptx, .xlsx, .pdf, .srt)",
        "Download Translated File": "翻訳ファイルをダウンロード",
        "Status Message": "ステータスメッセージ",
        "Translate": "翻訳",
        "Local Network Mode (Restart to Apply)": "ローカルネットワークモード（再起動後に適用）",
        "Max Retries": "最大再試行回数",
        "Excel Mode": "翻訳漏れ？モード2を試す",
        "Word Bilingual": "二言語対照を有効にする",
        "Excel Bilingual": "Excelバイリンガルモードを有効にする",
        "PDF Bilingual": "PDFバイリンガルモードを有効にする",
        "Continue Translation": "翻訳を続ける",
        "Thread Count": "スレッド数",
        "Stop Translation": "翻訳を停止",
        "Stopping": "停止中...",
        "Glossary": "用語集",
        "Add Glossary": "+ 用語集を追加...",
        "Drop CSV file here": "CSVファイルをドロップまたはクリック",
        "Add Custom Language": "+ カスタム言語を追加...",
        "New Language Name": "新しい言語名",
        "Language Name Placeholder": "例：クリンゴン語",
        "Create Language": "作成",
        # Status messages
        "Extracting text": "テキストを抽出中",
        "Removing duplicates": "重複を削除中",
        "Splitting text": "テキストを分割中",
        "Translating content": "コンテンツを翻訳中",
        "Translating": "翻訳中",
        "Checking results": "結果を確認中",
        "Restoring structure": "構造を復元中",
        "Generating output": "出力を生成中",
        "Extracting PDF content": "PDFコンテンツを抽出中",
        "Generating translated PDF": "翻訳済みPDFを生成中",
        "Translation completed": "翻訳完了",
        "Total tokens used": "合計トークン数",
        "Preparing content": "コンテンツを準備中",
        "Continuing from": "から継続",
        "Retry": "再試行",
        "Security Tips": "セキュリティに関するヒント",
        "Security Tips Content": "この機能は非LANモードでのみ使用できます。APIキーは個人のプライバシーデータであり、セキュリティリスクがあります。慎重に有効にしてください。",
        "Show API Key": "キーを表示",
        "Hide API Key": "キーを非表示",
        # Translation History
        "Translation History": "翻訳履歴",
        "Refresh Records": "更新",
        "Back": "戻る",
        "No translation records": "翻訳履歴がありません",
        "Time": "時間",
        "Duration": "所要時間",
        "Online": "オンライン",
        "Offline": "オフライン",
        "Open Output Folder": "出力フォルダを開く",
        "Open Log Folder": "ログフォルダを開く",
        "Status": "ステータス",
        "Success": "成功",
        "Failed": "失敗",
        "Stopped": "停止済み",
        "Tokens": "トークン"
    },
    # Spanish
    "es": {
        "Source Language": "Idioma de origen",
        "Target Language": "Idioma de destino",
        "Use Online Model": "Usar modelo en línea",
        "Models": "Modelos",
        "API Key": "Clave API",
        "Remember Key": "Recordar clave",
        "Enter your API key here": "Ingrese su clave API aquí",
        "Upload File": "Subir archivo (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "Subir archivos (.docx, .pptx, .xlsx, .pdf, .srt)",
        "Download Translated File": "Descargar archivo traducido",
        "Status Message": "Mensaje de estado",
        "Translate": "Traducir",
        "Local Network Mode (Restart to Apply)": "Modo de red local (Reiniciar para aplicar)",
        "Max Retries": "Número máximo de reintentos",
        "Excel Mode": "¿Traducción incompleta? Probar modo 2",
        "Word Bilingual": "Habilitar comparación bilingüe",
        "Excel Bilingual": "Habilitar modo bilingüe de Excel",
        "PDF Bilingual": "Habilitar modo bilingüe de PDF",
        "Continue Translation": "Continuar traducción",
        "Thread Count": "Número de hilos",
        "Stop Translation": "Detener traducción",
        "Stopping": "Deteniendo...",
        "Glossary": "Glosario",
        "Add Glossary": "+ Agregar glosario...",
        "Drop CSV file here": "Suelte el archivo CSV aquí o haga clic",
        "Add Custom Language": "+ Agregar idioma...",
        "New Language Name": "Nombre del nuevo idioma",
        "Language Name Placeholder": "ej. Klingon",
        "Create Language": "Crear",
        # Status messages
        "Extracting text": "Extrayendo texto",
        "Removing duplicates": "Eliminando duplicados",
        "Splitting text": "Dividiendo texto",
        "Translating content": "Traduciendo contenido",
        "Translating": "Traduciendo",
        "Checking results": "Verificando resultados",
        "Restoring structure": "Restaurando estructura",
        "Generating output": "Generando salida",
        "Extracting PDF content": "Extrayendo contenido del PDF",
        "Generating translated PDF": "Generando PDF traducido",
        "Translation completed": "Traducción completada",
        "Total tokens used": "Tokens totales utilizados",
        "Preparing content": "Preparando contenido",
        "Continuing from": "Continuando desde",
        "Retry": "Reintento",
        "Security Tips": "Consejos de seguridad",
        "Security Tips Content": "Esta función solo está disponible en modo no LAN. Las claves API son datos privados con riesgos de seguridad. Por favor, habilite con precaución.",
        "Show API Key": "Mostrar clave",
        "Hide API Key": "Ocultar clave",
        # Translation History
        "Translation History": "Historial de traducción",
        "Refresh Records": "Actualizar",
        "Back": "Volver",
        "No translation records": "No hay registros de traducción",
        "Time": "Tiempo",
        "Duration": "Duración",
        "Online": "En línea",
        "Offline": "Sin conexión",
        "Open Output Folder": "Abrir carpeta de salida",
        "Open Log Folder": "Abrir carpeta de registros",
        "Status": "Estado",
        "Success": "Éxito",
        "Failed": "Fallido",
        "Stopped": "Detenido",
        "Tokens": "Tokens"
    },
    # French
    "fr": {
        "Source Language": "Langue source",
        "Target Language": "Langue cible",
        "Use Online Model": "Utiliser un modèle en ligne",
        "Models": "Modèles",
        "API Key": "Clé API",
        "Remember Key": "Se souvenir de la clé",
        "Enter your API key here": "Entrez votre clé API ici",
        "Upload File": "Télécharger le fichier (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "Télécharger les fichiers (.docx, .pptx, .xlsx, .pdf, .srt)",
        "Download Translated File": "Télécharger le fichier traduit",
        "Status Message": "Message d'état",
        "Translate": "Traduire",
        "Local Network Mode (Restart to Apply)": "Mode réseau local (Redémarrer pour appliquer)",
        "Max Retries": "Nombre maximal de tentatives",
        "Excel Mode": "Traduction incomplète ? Essayez le mode 2",
        "Word Bilingual": "Activer la comparaison bilingue",
        "Excel Bilingual": "Activer le mode bilingue Excel",
        "PDF Bilingual": "Activer le mode bilingue PDF",
        "Continue Translation": "Continuer la traduction",
        "Thread Count": "Nombre de threads",
        "Stop Translation": "Arrêter la traduction",
        "Stopping": "Arrêt en cours...",
        "Glossary": "Glossaire",
        "Add Glossary": "+ Ajouter un glossaire...",
        "Drop CSV file here": "Déposez le fichier CSV ici ou cliquez",
        "Add Custom Language": "+ Ajouter une langue...",
        "New Language Name": "Nom de la nouvelle langue",
        "Language Name Placeholder": "ex. Klingon",
        "Create Language": "Créer",
        # Status messages
        "Extracting text": "Extraction du texte",
        "Removing duplicates": "Suppression des doublons",
        "Splitting text": "Division du texte",
        "Translating content": "Traduction du contenu",
        "Translating": "Traduction",
        "Checking results": "Vérification des résultats",
        "Restoring structure": "Restauration de la structure",
        "Generating output": "Génération de la sortie",
        "Extracting PDF content": "Extraction du contenu PDF",
        "Generating translated PDF": "Génération du PDF traduit",
        "Translation completed": "Traduction terminée",
        "Total tokens used": "Tokens totaux utilisés",
        "Preparing content": "Préparation du contenu",
        "Continuing from": "Continuer depuis",
        "Retry": "Réessayer",
        "Security Tips": "Conseils de sécurité",
        "Security Tips Content": "Cette fonction n'est disponible qu'en mode non-LAN. Les clés API sont des données privées avec des risques de sécurité. Veuillez activer avec prudence.",
        "Show API Key": "Afficher la clé",
        "Hide API Key": "Masquer la clé",
        # Translation History
        "Translation History": "Historique des traductions",
        "Refresh Records": "Actualiser",
        "Back": "Retour",
        "No translation records": "Aucun historique de traduction",
        "Time": "Heure",
        "Duration": "Durée",
        "Online": "En ligne",
        "Offline": "Hors ligne",
        "Open Output Folder": "Ouvrir le dossier de sortie",
        "Open Log Folder": "Ouvrir le dossier des journaux",
        "Status": "Statut",
        "Success": "Succès",
        "Failed": "Échec",
        "Stopped": "Arrêté",
        "Tokens": "Tokens"
    },
    # German
    "de": {
        "Source Language": "Ausgangssprache",
        "Target Language": "Zielsprache",
        "Use Online Model": "Online-Modell verwenden",
        "Models": "Modelle",
        "API Key": "API-Schlüssel",
        "Remember Key": "Schlüssel merken",
        "Enter your API key here": "Geben Sie hier Ihren API-Schlüssel ein",
        "Upload File": "Datei hochladen (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "Dateien hochladen (.docx, .pptx, .xlsx, .pdf, .srt)",
        "Download Translated File": "Übersetzte Datei herunterladen",
        "Status Message": "Statusnachricht",
        "Translate": "Übersetzen",
        "Local Network Mode (Restart to Apply)": "Lokaler Netzwerkmodus (Neustart erforderlich)",
        "Max Retries": "Maximale Wiederholungsversuche",
        "Excel Mode": "Übersetzung unvollständig? Versuchen Sie Modus 2",
        "Word Bilingual": "Zweisprachigen Vergleich aktivieren",
        "Excel Bilingual": "Excel-Zweisprachenmodus aktivieren",
        "PDF Bilingual": "PDF-Zweisprachenmodus aktivieren",
        "Continue Translation": "Übersetzung fortsetzen",
        "Thread Count": "Thread-Anzahl",
        "Stop Translation": "Übersetzung stoppen",
        "Stopping": "Stoppe...",
        "Glossary": "Glossar",
        "Add Glossary": "+ Glossar hinzufügen...",
        "Drop CSV file here": "CSV-Datei hier ablegen oder klicken",
        "Add Custom Language": "+ Sprache hinzufügen...",
        "New Language Name": "Name der neuen Sprache",
        "Language Name Placeholder": "z.B. Klingonisch",
        "Create Language": "Erstellen",
        # Status messages
        "Extracting text": "Text extrahieren",
        "Removing duplicates": "Duplikate entfernen",
        "Splitting text": "Text aufteilen",
        "Translating content": "Inhalt übersetzen",
        "Translating": "Übersetze",
        "Checking results": "Ergebnisse prüfen",
        "Restoring structure": "Struktur wiederherstellen",
        "Generating output": "Ausgabe generieren",
        "Extracting PDF content": "PDF-Inhalt extrahieren",
        "Generating translated PDF": "Übersetztes PDF generieren",
        "Translation completed": "Übersetzung abgeschlossen",
        "Total tokens used": "Verwendete Tokens gesamt",
        "Preparing content": "Inhalt vorbereiten",
        "Continuing from": "Fortsetzen von",
        "Retry": "Wiederholen",
        "Security Tips": "Sicherheitshinweise",
        "Security Tips Content": "Diese Funktion ist nur im Nicht-LAN-Modus verfügbar. API-Schlüssel sind private Daten mit Sicherheitsrisiken. Bitte mit Vorsicht aktivieren.",
        "Show API Key": "Schlüssel anzeigen",
        "Hide API Key": "Schlüssel verbergen",
        # Translation History
        "Translation History": "Übersetzungsverlauf",
        "Refresh Records": "Aktualisieren",
        "Back": "Zurück",
        "No translation records": "Keine Übersetzungseinträge",
        "Time": "Zeit",
        "Duration": "Dauer",
        "Online": "Online",
        "Offline": "Offline",
        "Open Output Folder": "Ausgabeordner öffnen",
        "Open Log Folder": "Protokollordner öffnen",
        "Status": "Status",
        "Success": "Erfolg",
        "Failed": "Fehlgeschlagen",
        "Stopped": "Gestoppt",
        "Tokens": "Tokens"
    },
    # Italian
    "it": {
        "Source Language": "Lingua di origine",
        "Target Language": "Lingua di destinazione",
        "Use Online Model": "Usa modello online",
        "Models": "Modelli",
        "API Key": "Chiave API",
        "Remember Key": "Ricorda chiave",
        "Enter your API key here": "Inserisci qui la tua chiave API",
        "Upload File": "Carica file (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "Carica file (.docx, .pptx, .xlsx, .pdf, .srt)",
        "Download Translated File": "Scarica file tradotto",
        "Status Message": "Messaggio di stato",
        "Translate": "Traduci",
        "Local Network Mode (Restart to Apply)": "Modalità rete locale (Riavvia per applicare)",
        "Max Retries": "Numero massimo di tentativi",
        "Excel Mode": "Traduzione incompleta? Prova la modalità 2",
        "Word Bilingual": "Abilita confronto bilingue",
        "Excel Bilingual": "Abilita modalità bilingue Excel",
        "PDF Bilingual": "Abilita modalità bilingue PDF",
        "Continue Translation": "Continua traduzione",
        "Thread Count": "Numero di thread",
        "Stop Translation": "Interrompi traduzione",
        "Stopping": "Interruzione in corso...",
        "Glossary": "Glossario",
        "Add Glossary": "+ Aggiungi glossario...",
        "Drop CSV file here": "Trascina il file CSV qui o clicca",
        "Add Custom Language": "+ Aggiungi lingua...",
        "New Language Name": "Nome della nuova lingua",
        "Language Name Placeholder": "es. Klingon",
        "Create Language": "Crea",
        # Status messages
        "Extracting text": "Estrazione del testo",
        "Removing duplicates": "Rimozione dei duplicati",
        "Splitting text": "Divisione del testo",
        "Translating content": "Traduzione del contenuto",
        "Translating": "Traduzione",
        "Checking results": "Verifica dei risultati",
        "Restoring structure": "Ripristino della struttura",
        "Generating output": "Generazione dell'output",
        "Extracting PDF content": "Estrazione del contenuto PDF",
        "Generating translated PDF": "Generazione del PDF tradotto",
        "Translation completed": "Traduzione completata",
        "Total tokens used": "Token totali utilizzati",
        "Preparing content": "Preparazione del contenuto",
        "Continuing from": "Continua da",
        "Retry": "Riprova",
        "Security Tips": "Suggerimenti per la sicurezza",
        "Security Tips Content": "Questa funzione è disponibile solo in modalità non-LAN. Le chiavi API sono dati privati con rischi per la sicurezza. Si prega di abilitare con cautela.",
        "Show API Key": "Mostra chiave",
        "Hide API Key": "Nascondi chiave",
        # Translation History
        "Translation History": "Cronologia traduzioni",
        "Refresh Records": "Aggiorna",
        "Back": "Indietro",
        "No translation records": "Nessun record di traduzione",
        "Time": "Ora",
        "Duration": "Durata",
        "Online": "Online",
        "Offline": "Offline",
        "Open Output Folder": "Apri cartella di output",
        "Open Log Folder": "Apri cartella dei log",
        "Status": "Stato",
        "Success": "Successo",
        "Failed": "Fallito",
        "Stopped": "Interrotto",
        "Tokens": "Token"
    },
    # Portuguese
    "pt": {
        "Source Language": "Idioma de origem",
        "Target Language": "Idioma de destino",
        "Use Online Model": "Usar modelo online",
        "Models": "Modelos",
        "API Key": "Chave de API",
        "Remember Key": "Lembrar chave",
        "Enter your API key here": "Digite sua chave de API aqui",
        "Upload File": "Enviar arquivo (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "Enviar arquivos (.docx, .pptx, .xlsx, .pdf, .srt)",
        "Download Translated File": "Baixar arquivo traduzido",
        "Status Message": "Mensagem de status",
        "Translate": "Traduzir",
        "Local Network Mode (Restart to Apply)": "Modo de rede local (Reiniciar para aplicar)",
        "Max Retries": "Número máximo de tentativas",
        "Excel Mode": "Tradução incompleta? Tente o modo 2",
        "Word Bilingual": "Ativar comparação bilíngue",
        "Excel Bilingual": "Ativar modo bilíngue Excel",
        "PDF Bilingual": "Ativar modo bilíngue PDF",
        "Continue Translation": "Continuar tradução",
        "Thread Count": "Número de threads",
        "Stop Translation": "Parar tradução",
        "Stopping": "Parando...",
        "Glossary": "Glossário",
        "Add Glossary": "+ Adicionar glossário...",
        "Drop CSV file here": "Solte o arquivo CSV aqui ou clique",
        "Add Custom Language": "+ Adicionar idioma...",
        "New Language Name": "Nome do novo idioma",
        "Language Name Placeholder": "ex. Klingon",
        "Create Language": "Criar",
        # Status messages
        "Extracting text": "Extraindo texto",
        "Removing duplicates": "Removendo duplicatas",
        "Splitting text": "Dividindo texto",
        "Translating content": "Traduzindo conteúdo",
        "Translating": "Traduzindo",
        "Checking results": "Verificando resultados",
        "Restoring structure": "Restaurando estrutura",
        "Generating output": "Gerando saída",
        "Extracting PDF content": "Extraindo conteúdo do PDF",
        "Generating translated PDF": "Gerando PDF traduzido",
        "Translation completed": "Tradução concluída",
        "Total tokens used": "Tokens totais utilizados",
        "Preparing content": "Preparando conteúdo",
        "Continuing from": "Continuando de",
        "Retry": "Tentar novamente",
        "Security Tips": "Dicas de segurança",
        "Security Tips Content": "Este recurso está disponível apenas no modo não-LAN. As chaves de API são dados privados com riscos de segurança. Por favor, habilite com cautela.",
        "Show API Key": "Mostrar chave",
        "Hide API Key": "Ocultar chave",
        # Translation History
        "Translation History": "Histórico de traduções",
        "Refresh Records": "Atualizar",
        "Back": "Voltar",
        "No translation records": "Nenhum registro de tradução",
        "Time": "Hora",
        "Duration": "Duração",
        "Online": "Online",
        "Offline": "Offline",
        "Open Output Folder": "Abrir pasta de saída",
        "Open Log Folder": "Abrir pasta de logs",
        "Status": "Status",
        "Success": "Sucesso",
        "Failed": "Falhou",
        "Stopped": "Parado",
        "Tokens": "Tokens"
    },
    # Russian
    "ru": {
        "Source Language": "Исходный язык",
        "Target Language": "Целевой язык",
        "Use Online Model": "Использовать онлайн-модель",
        "Models": "Модели",
        "API Key": "API-ключ",
        "Remember Key": "Запомнить ключ",
        "Enter your API key here": "Введите ваш API-ключ здесь",
        "Upload File": "Загрузить файл (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "Загрузить файлы (.docx, .pptx, .xlsx, .pdf, .srt)",
        "Download Translated File": "Скачать переведенный файл",
        "Status Message": "Статусное сообщение",
        "Translate": "Перевести",
        "Local Network Mode (Restart to Apply)": "Режим локальной сети (Перезагрузка для применения)",
        "Max Retries": "Максимальное количество повторных попыток",
        "Excel Mode": "Перевод неполный? Попробуйте режим 2",
        "Word Bilingual": "Включить двуязычное сравнение",
        "Excel Bilingual": "Включить двуязычный режим Excel",
        "PDF Bilingual": "Включить двуязычный режим PDF",
        "Continue Translation": "Продолжить перевод",
        "Thread Count": "Количество потоков",
        "Stop Translation": "Остановить перевод",
        "Stopping": "Остановка...",
        "Glossary": "Глоссарий",
        "Add Glossary": "+ Добавить глоссарий...",
        "Drop CSV file here": "Перетащите CSV файл сюда или нажмите",
        "Add Custom Language": "+ Добавить язык...",
        "New Language Name": "Название нового языка",
        "Language Name Placeholder": "напр. Клингонский",
        "Create Language": "Создать",
        # Status messages
        "Extracting text": "Извлечение текста",
        "Removing duplicates": "Удаление дубликатов",
        "Splitting text": "Разделение текста",
        "Translating content": "Перевод содержимого",
        "Translating": "Перевод",
        "Checking results": "Проверка результатов",
        "Restoring structure": "Восстановление структуры",
        "Generating output": "Генерация вывода",
        "Extracting PDF content": "Извлечение содержимого PDF",
        "Generating translated PDF": "Генерация переведённого PDF",
        "Translation completed": "Перевод завершён",
        "Total tokens used": "Всего использовано токенов",
        "Preparing content": "Подготовка содержимого",
        "Continuing from": "Продолжить с",
        "Retry": "Повторить",
        "Security Tips": "Советы по безопасности",
        "Security Tips Content": "Эта функция доступна только в режиме без LAN. API-ключи — это личные данные с рисками безопасности. Пожалуйста, включайте с осторожностью.",
        "Show API Key": "Показать ключ",
        "Hide API Key": "Скрыть ключ",
        # Translation History
        "Translation History": "История переводов",
        "Refresh Records": "Обновить",
        "Back": "Назад",
        "No translation records": "Нет записей о переводах",
        "Time": "Время",
        "Duration": "Длительность",
        "Online": "Онлайн",
        "Offline": "Офлайн",
        "Open Output Folder": "Открыть папку вывода",
        "Open Log Folder": "Открыть папку журналов",
        "Status": "Статус",
        "Success": "Успешно",
        "Failed": "Ошибка",
        "Stopped": "Остановлено",
        "Tokens": "Токены"
    },
    # Korean
    "ko": {
        "Source Language": "소스 언어",
        "Target Language": "대상 언어",
        "Use Online Model": "온라인 모델 사용",
        "Models": "모델",
        "API Key": "API 키",
        "Remember Key": "키 기억하기",
        "Enter your API key here": "여기에 API 키를 입력하세요",
        "Upload File": "파일 업로드 (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "파일 업로드 (.docx, .pptx, .xlsx, .pdf, .srt)",
        "Download Translated File": "번역된 파일 다운로드",
        "Status Message": "상태 메시지",
        "Translate": "번역",
        "Local Network Mode (Restart to Apply)": "로컬 네트워크 모드 (적용하려면 재시작)",
        "Max Retries": "최대 재시도 횟수",
        "Excel Mode": "번역이 누락되었나요? 모드 2 시도",
        "Word Bilingual": "이중 언어 비교 활성화",
        "Excel Bilingual": "Excel 이중 언어 모드 활성화",
        "PDF Bilingual": "PDF 이중 언어 모드 활성화",
        "Continue Translation": "번역 계속하기",
        "Thread Count": "스레드 수",
        "Stop Translation": "번역 중지",
        "Stopping": "중지 중...",
        "Glossary": "용어집",
        "Add Glossary": "+ 용어집 추가...",
        "Drop CSV file here": "CSV 파일을 여기에 놓거나 클릭",
        "Add Custom Language": "+ 언어 추가...",
        "New Language Name": "새 언어 이름",
        "Language Name Placeholder": "예: 클링온어",
        "Create Language": "생성",
        # Status messages
        "Extracting text": "텍스트 추출 중",
        "Removing duplicates": "중복 제거 중",
        "Splitting text": "텍스트 분할 중",
        "Translating content": "콘텐츠 번역 중",
        "Translating": "번역 중",
        "Checking results": "결과 확인 중",
        "Restoring structure": "구조 복원 중",
        "Generating output": "출력 생성 중",
        "Extracting PDF content": "PDF 콘텐츠 추출 중",
        "Generating translated PDF": "번역된 PDF 생성 중",
        "Translation completed": "번역 완료",
        "Total tokens used": "총 사용 토큰",
        "Preparing content": "콘텐츠 준비 중",
        "Continuing from": "에서 계속",
        "Retry": "재시도",
        "Security Tips": "보안 팁",
        "Security Tips Content": "이 기능은 비LAN 모드에서만 사용할 수 있습니다. API 키는 보안 위험이 있는 개인 데이터입니다. 신중하게 활성화하십시오.",
        "Show API Key": "키 표시",
        "Hide API Key": "키 숨기기",
        # Translation History
        "Translation History": "번역 기록",
        "Refresh Records": "새로고침",
        "Back": "뒤로",
        "No translation records": "번역 기록이 없습니다",
        "Time": "시간",
        "Duration": "소요 시간",
        "Online": "온라인",
        "Offline": "오프라인",
        "Open Output Folder": "출력 폴더 열기",
        "Open Log Folder": "로그 폴더 열기",
        "Status": "상태",
        "Success": "성공",
        "Failed": "실패",
        "Stopped": "중지됨",
        "Tokens": "토큰"
    },
    # Thai
    "th": {
        "Source Language": "ภาษาต้นฉบับ",
        "Target Language": "ภาษาเป้าหมาย",
        "Use Online Model": "ใช้โมเดลออนไลน์",
        "Models": "โมเดล",
        "API Key": "คีย์ API",
        "Remember Key": "จำคีย์",
        "Enter your API key here": "ป้อนคีย์ API ของคุณที่นี่",
        "Upload File": "อัปโหลดไฟล์ (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "อัปโหลดไฟล์ (.docx, .pptx, .xlsx, .pdf, .srt)",
        "Download Translated File": "ดาวน์โหลดไฟล์ที่แปลแล้ว",
        "Status Message": "ข้อความสถานะ",
        "Translate": "แปล",
        "Local Network Mode (Restart to Apply)": "โหมดเครือข่ายท้องถิ่น (รีสตาร์ทเพื่อใช้งาน)",
        "Max Retries": "จำนวนการลองซ้ำสูงสุด",
        "Excel Mode": "การแปลขาดหายไป? ลองโหมด 2",
        "Word Bilingual": "เปิดใช้งานการเปรียบเทียบสองภาษา",
        "Excel Bilingual": "เปิดใช้งานโหมดสองภาษา Excel",
        "PDF Bilingual": "เปิดใช้งานโหมดสองภาษา PDF",
        "Continue Translation": "แปลต่อ",
        "Thread Count": "จำนวนเธรด",
        "Stop Translation": "หยุดการแปล",
        "Stopping": "กำลังหยุด...",
        "Glossary": "อภิธานศัพท์",
        "Add Glossary": "+ เพิ่มอภิธานศัพท์...",
        "Drop CSV file here": "วางไฟล์ CSV ที่นี่หรือคลิก",
        "Add Custom Language": "+ เพิ่มภาษา...",
        "New Language Name": "ชื่อภาษาใหม่",
        "Language Name Placeholder": "เช่น คลิงออน",
        "Create Language": "สร้าง",
        # Status messages
        "Extracting text": "กำลังดึงข้อความ",
        "Removing duplicates": "กำลังลบข้อความซ้ำ",
        "Splitting text": "กำลังแบ่งข้อความ",
        "Translating content": "กำลังแปลเนื้อหา",
        "Translating": "กำลังแปล",
        "Checking results": "กำลังตรวจสอบผลลัพธ์",
        "Restoring structure": "กำลังกู้คืนโครงสร้าง",
        "Generating output": "กำลังสร้างผลลัพธ์",
        "Extracting PDF content": "กำลังแยกเนื้อหา PDF",
        "Generating translated PDF": "กำลังสร้างไฟล์ PDF ที่แปลแล้ว",
        "Translation completed": "การแปลเสร็จสมบูรณ์",
        "Total tokens used": "โทเค็นทั้งหมดที่ใช้",
        "Preparing content": "กำลังเตรียมเนื้อหา",
        "Continuing from": "ดำเนินการต่อจาก",
        "Retry": "ลองใหม่",
        "Security Tips": "เคล็ดลับความปลอดภัย",
        "Security Tips Content": "ฟังก์ชันนี้ใช้ได้เฉพาะในโหมดที่ไม่ใช่ LAN คีย์ API เป็นข้อมูลส่วนตัวที่มีความเสี่ยงด้านความปลอดภัย กรุณาเปิดใช้งานด้วยความระมัดระวัง",
        "Show API Key": "แสดงคีย์",
        "Hide API Key": "ซ่อนคีย์",
        # Translation History
        "Translation History": "ประวัติการแปล",
        "Refresh Records": "รีเฟรช",
        "Back": "ย้อนกลับ",
        "No translation records": "ไม่มีประวัติการแปล",
        "Time": "เวลา",
        "Duration": "ระยะเวลา",
        "Online": "ออนไลน์",
        "Offline": "ออฟไลน์",
        "Open Output Folder": "เปิดโฟลเดอร์เอาต์พุต",
        "Open Log Folder": "เปิดโฟลเดอร์บันทึก",
        "Status": "สถานะ",
        "Success": "สำเร็จ",
        "Failed": "ล้มเหลว",
        "Stopped": "หยุดแล้ว",
        "Tokens": "โทเค็น"
    },
    # Vietnamese
    "vi": {
        "Source Language": "Ngôn ngữ nguồn",
        "Target Language": "Ngôn ngữ đích",
        "Use Online Model": "Sử dụng mô hình trực tuyến",
        "Models": "Mô hình",
        "API Key": "Khóa API",
        "Remember Key": "Ghi nhớ khóa",
        "Enter your API key here": "Nhập khóa API của bạn tại đây",
        "Upload File": "Tải lên tệp (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "Tải lên tệp (.docx, .pptx, .xlsx, .pdf, .srt)",
        "Download Translated File": "Tải xuống tệp đã dịch",
        "Status Message": "Thông báo trạng thái",
        "Translate": "Dịch",
        "Local Network Mode (Restart to Apply)": "Chế độ mạng cục bộ (Khởi động lại để áp dụng)",
        "Max Retries": "Số lần thử lại tối đa",
        "Excel Mode": "Bị bỏ sót khi dịch? Thử chế độ 2",
        "Word Bilingual": "Bật so sánh song ngữ",
        "Excel Bilingual": "Bật chế độ song ngữ Excel",
        "PDF Bilingual": "Bật chế độ song ngữ PDF",
        "Continue Translation": "Tiếp tục dịch",
        "Thread Count": "Số lượng luồng",
        "Stop Translation": "Dừng dịch",
        "Stopping": "Đang dừng...",
        "Glossary": "Bảng thuật ngữ",
        "Add Glossary": "+ Thêm bảng thuật ngữ...",
        "Drop CSV file here": "Thả tệp CSV vào đây hoặc nhấp",
        "Add Custom Language": "+ Thêm ngôn ngữ...",
        "New Language Name": "Tên ngôn ngữ mới",
        "Language Name Placeholder": "vd. Klingon",
        "Create Language": "Tạo",
        # Status messages
        "Extracting text": "Đang trích xuất văn bản",
        "Removing duplicates": "Đang xóa bản sao",
        "Splitting text": "Đang chia văn bản",
        "Translating content": "Đang dịch nội dung",
        "Translating": "Đang dịch",
        "Checking results": "Đang kiểm tra kết quả",
        "Restoring structure": "Đang khôi phục cấu trúc",
        "Generating output": "Đang tạo đầu ra",
        "Extracting PDF content": "Đang trích xuất nội dung PDF",
        "Generating translated PDF": "Đang tạo tệp PDF đã dịch",
        "Translation completed": "Dịch hoàn tất",
        "Total tokens used": "Tổng số token đã sử dụng",
        "Preparing content": "Đang chuẩn bị nội dung",
        "Continuing from": "Tiếp tục từ",
        "Retry": "Thử lại",
        "Security Tips": "Mẹo bảo mật",
        "Security Tips Content": "Tính năng này chỉ khả dụng ở chế độ không phải LAN. Khóa API là dữ liệu riêng tư có rủi ro bảo mật. Vui lòng bật một cách cẩn thận.",
        "Show API Key": "Hiện khóa",
        "Hide API Key": "Ẩn khóa",
        # Translation History
        "Translation History": "Lịch sử dịch",
        "Refresh Records": "Làm mới",
        "Back": "Quay lại",
        "No translation records": "Không có lịch sử dịch",
        "Time": "Thời gian",
        "Duration": "Thời lượng",
        "Online": "Trực tuyến",
        "Offline": "Ngoại tuyến",
        "Open Output Folder": "Mở thư mục đầu ra",
        "Open Log Folder": "Mở thư mục nhật ký",
        "Status": "Trạng thái",
        "Success": "Thành công",
        "Failed": "Thất bại",
        "Stopped": "Đã dừng",
        "Tokens": "Token"
    }
}