import os
import shutil

def create_custom_language_prompt_file(custom_language_name):
    """Create a new prompt file for a custom language by copying en.json"""
    prompts_dir = os.path.join("config", "prompts")
    source_file = os.path.join(prompts_dir, "en.json")
    target_file = os.path.join(prompts_dir, f"{custom_language_name}.json")
    
    try:
        # Ensure the prompts directory exists
        os.makedirs(prompts_dir, exist_ok=True)
        
        # Copy en.json to the new custom language file
        if os.path.exists(source_file):
            shutil.copy2(source_file, target_file)
            return True, f"Created prompt file for {custom_language_name}"
        else:
            return False, "Source file en.json not found"
    except Exception as e:
        return False, f"Error creating prompt file: {str(e)}"

def add_custom_language(custom_language_name):
    """Add a custom language to the system"""
    if not custom_language_name or custom_language_name.strip() == "":
        return False, "Language name cannot be empty"
    
    custom_language_name = custom_language_name.strip()
    
    # Create the prompt file
    success, message = create_custom_language_prompt_file(custom_language_name)
    
    if success:
        return True, f"Custom language '{custom_language_name}' added successfully"
    else:
        return False, message


def get_available_languages():
    """Read language files from config/prompts directory and return display names"""
    prompts_dir = os.path.join("config", "prompts")
    available_languages = []
    
    if os.path.exists(prompts_dir):
        # Get all .json files in the prompts directory
        for filename in os.listdir(prompts_dir):
            if filename.endswith(".json"):
                # Get language code without extension
                lang_code = os.path.splitext(filename)[0]
                
                # Find the display name from LANGUAGE_MAP
                display_name_found = False
                for display_name, code in LANGUAGE_MAP.items():
                    if code == lang_code:
                        available_languages.append(display_name)
                        display_name_found = True
                        break
                
                # If language code not found in LANGUAGE_MAP, add it directly
                if not display_name_found:
                    available_languages.append(lang_code)  # Changed from lang_code.upper()
    
    # If no languages found, return default list
    if not available_languages:
        available_languages = [
            "English", "中文", "繁體中文", "日本語", "Español", 
            "Français", "Deutsch", "Italiano", "Português", 
            "Русский", "한국어", "ภาษาไทย", "Tiếng Việt"
        ]
    
    return sorted(set(available_languages))

def get_language_code(display_name):
    """Get language code from display name, supporting custom languages"""
    # First check if it's in the existing LANGUAGE_MAP
    if display_name in LANGUAGE_MAP:
        return LANGUAGE_MAP[display_name]
    
    # If not found, assume the display name is the language code in uppercase
    # Convert it to lowercase to match file naming convention
    return display_name.lower()

LANGUAGE_MAP = {
    "日本語": "ja",
    "中文": "zh",
    "繁體中文": "zh-Hant",
    "English": "en",
    "Español": "es",
    "Français": "fr",
    "Deutsch": "de",
    "Italiano": "it",
    "Português": "pt",
    "Русский": "ru",
    "한국어": "ko",
    "ภาษาไทย": "th",
    "Tiếng Việt": "vi"
}

LABEL_TRANSLATIONS = {
    # English
    "en": {
        "Source Language": "Source Language",
        "Target Language": "Target Language",
        "Use Online Model": "Use Online Model",
        "Models": "Models",
        "API Key": "API Key",
        "Remember Key": "Remember Key",
        "Enter your API key here": "Enter your API key here",
        "Upload File": "Upload Office File (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "Upload Files",
        "Download Translated File": "Download Translated File",
        "Status Message": "Status Message",
        "Translate": "Translate",
        "Local Network Mode (Restart to Apply)": "Local Network Mode (Restart to Apply)",
        "Max Retries": "Max Retries",
        "Excel Mode": "Missing Translation? Try Mode 2",
        "Word Bilingual": "Enable Bilingual Comparison",
        "Excel Bilingual": "Enable Excel Bilingual Mode",
        "PDF Bilingual": "Enable PDF Bilingual Mode",
        "Subtitle Bilingual": "Enable Bilingual Subtitles",
        "TXT Bilingual": "Enable TXT Bilingual Mode",
        "MD Bilingual": "Enable Markdown Bilingual Mode",
        "EPUB Bilingual": "Enable EPUB Bilingual Mode",
        "HTML Bilingual": "Enable HTML Bilingual Mode",
        "Continue Translation": "Continue Translation",
        "Thread Count": "Thread Count",
        "Stop Translation": "Stop Translation",
        "Stopping": "Stopping...",
        "Glossary": "Glossary",
        "Add Glossary": "+ Add Glossary...",
        "Drop CSV file here": "Drop CSV file here or click to browse",
        "Add Custom Language": "+ Add Custom...",
        "New Language Name": "New language name",
        "Language Name Placeholder": "e.g. Klingon",
        "Create Language": "Create",
        # Status messages
        "Extracting text": "Extracting text",
        "Removing duplicates": "Removing duplicates",
        "Splitting text": "Splitting text",
        "Translating content": "Translating content",
        "Translating": "Translating",
        "Checking results": "Checking results",
        "Restoring structure": "Restoring structure",
        "Generating output": "Generating output",
        "Extracting PDF content": "Extracting PDF content",
        "Generating translated PDF": "Generating translated PDF",
        "Translation completed": "Translation completed",
        "Total tokens used": "Total tokens used",
        "Preparing content": "Preparing content",
        "Continuing from": "Continuing from",
        "Retry": "Retry",
        "Show API Key": "Show API Key",
        "Hide API Key": "Hide API Key",
        "Security Tips": "Security Tips",
        "Security Tips Content": "This feature is only available in non-LAN mode. API keys are private data with security risks. Please enable with caution.",
        # Tab labels
        "Settings": "Settings",
        "History": "History",
        "Interface Language": "Interface Language",
        # Translation History
        "Translation History": "Translation History",
        "Refresh Records": "Refresh",
        "Back": "Back",
        "No translation records": "No translation records",
        "Time": "Time",
        "Duration": "Duration",
        "Online": "Online",
        "Offline": "Offline",
        "Open Output Folder": "Open Output Folder",
        "Open Log Folder": "Open Log Folder",
        "Status": "Status",
        "Success": "Success",
        "Failed": "Failed",
        "Stopped": "Stopped",
        "Tokens": "Tokens",
        # Glossary editor
        "Edit Glossary": "Edit Glossary",
        "Load Glossary": "Load Glossary",
        "Save Glossary": "Save Glossary",
        # Settings extras
        "AI Glossary Extraction": "AI Glossary Extraction",
        "AI Glossary Extraction Info": "Extract terms with the LLM before translating",
        "RPM Limit (0 = unlimited, restart to apply)": "RPM Limit (0 = unlimited, restart to apply)",
        "Optional Modules": "Optional Modules",
        # Runtime messages
        "Please select file(s) to translate.": "Please select file(s) to translate.",
        "API key is required for online models.": "API key is required for online models.",
        "Translation stopped by user.": "Translation stopped by user.",
        "No supported files found.": "No supported files found.",
        "Please select a model first": "Please select a model first.",
        "No Local Model Placeholder": "No local model detected — install Ollama or enable online models in Settings",
        "Progress Saved Hint": "Progress saved. Re-upload the same file and click 'Continue Translation' to resume.",
        "Unfinished Translation Detected": "Unfinished translation detected — you can click 'Continue Translation'.",
        "API Auth Error": "API key is invalid or expired. Please check the API Key at the top of the Translate tab.",
        "API Quota Error": "Insufficient balance/quota. Please top up or switch to another key.",
        "API Keys Exhausted": "All API keys failed (invalid or out of quota). Please replace the key(s).",
        "Completed Files": "Completed {done}/{total}",
        "Missing Segments": "{count} segment(s) missing",
        "Segments": "segments",
        # Proofread tab
        "Proofread": "Proofread",
        "Proofread Document": "Document",
        "Refresh List": "Refresh List",
        "Save Edits": "Save Edits",
        "Re-export": "Re-export",
        "Original Text": "Original",
        "Translated Text": "Translation",
        "Edits saved": "Saved {count} edited row(s).",
        "Row count mismatch": "Row count mismatch: expected {expected}, got {got}. Edits not saved.",
        "No proofread documents": "No proofreadable documents found. Finish a translation first (PDF is not supported).",
        "Proofread folder missing": "Translation data not found: {name}",
        "Export completed": "Re-export completed",
        "Loaded entries": "Loaded {count} row(s) from {name}"
    },
    # Simplified Chinese
    "zh": {
        "Source Language": "源语言",
        "Target Language": "目标语言",
        "Use Online Model": "使用在线模型",
        "Models": "模型",
        "API Key": "API 密钥",
        "Remember Key": "记住密钥",
        "Enter your API key here": "在此输入您的 API 密钥",
        "Upload File": "上传文件 (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "上传文件",
        "Download Translated File": "下载翻译文件",
        "Status Message": "状态消息",
        "Translate": "翻译",
        "Local Network Mode (Restart to Apply)": "局域网模式（重启后生效）",
        "Max Retries": "最大重试次数",
        "Excel Mode": "有漏翻？尝试模式2",
        "Word Bilingual": "启用双语对照",
        "Excel Bilingual": "Excel 双语模式",
        "PDF Bilingual": "PDF 双语模式",
        "Subtitle Bilingual": "双语字幕",
        "TXT Bilingual": "TXT 双语对照",
        "MD Bilingual": "Markdown 双语对照",
        "EPUB Bilingual": "EPUB 双语对照",
        "HTML Bilingual": "HTML 双语对照",
        "Continue Translation": "继续翻译",
        "Thread Count": "线程数量",
        "Stop Translation": "停止翻译",
        "Stopping": "正在停止...",
        "Glossary": "词汇表",
        "Add Glossary": "+ 添加词汇表...",
        "Drop CSV file here": "拖放CSV文件或点击浏览",
        "Add Custom Language": "+ 添加自定义语言...",
        "New Language Name": "新语言名称",
        "Language Name Placeholder": "例如：克林贡语",
        "Create Language": "创建",
        # Status messages
        "Extracting text": "正在提取文本",
        "Removing duplicates": "正在去除重复",
        "Splitting text": "正在拆分文本",
        "Translating content": "正在翻译内容",
        "Translating": "翻译中",
        "Checking results": "正在检查结果",
        "Restoring structure": "正在恢复结构",
        "Generating output": "正在生成输出",
        "Extracting PDF content": "正在提取PDF内容",
        "Generating translated PDF": "正在生成翻译后的PDF文件",
        "Translation completed": "翻译完成",
        "Total tokens used": "本次共消耗tokens",
        "Preparing content": "正在准备内容",
        "Continuing from": "继续自",
        "Retry": "重试",
        "Show API Key": "显示密钥",
        "Hide API Key": "隐藏密钥",
        "Security Tips": "安全提示",
        "Security Tips Content": "此功能仅在非局域网模式下可用。密钥为个人隐私数据，存在安全风险，请确认后谨慎开启。",
        # Tab labels
        "Settings": "设置",
        "History": "历史记录",
        "Interface Language": "界面语言",
        # Translation History
        "Translation History": "翻译记录",
        "Refresh Records": "刷新",
        "Back": "返回",
        "No translation records": "暂无翻译记录",
        "Time": "时间",
        "Duration": "耗时",
        "Online": "在线",
        "Offline": "离线",
        "Open Output Folder": "打开输出文件夹",
        "Open Log Folder": "打开日志文件夹",
        "Status": "状态",
        "Success": "成功",
        "Failed": "失败",
        "Stopped": "已停止",
        "Tokens": "Tokens",
        # Glossary editor
        "Edit Glossary": "编辑词汇表",
        "Load Glossary": "加载词汇表",
        "Save Glossary": "保存词汇表",
        # Settings extras
        "AI Glossary Extraction": "AI 术语提取",
        "AI Glossary Extraction Info": "翻译前使用大模型自动提取术语",
        "RPM Limit (0 = unlimited, restart to apply)": "RPM 限制（0 为不限制，重启后生效）",
        "Optional Modules": "可选模块",
        # Runtime messages
        "Please select file(s) to translate.": "请选择要翻译的文件。",
        "API key is required for online models.": "使用在线模型需要填写 API Key。",
        "Translation stopped by user.": "翻译已被用户停止。",
        "No supported files found.": "未找到支持的文件。",
        "Please select a model first": "请先选择模型。",
        "No Local Model Placeholder": "未检测到本地模型 — 安装 Ollama 或在设置中启用在线模型",
        "Progress Saved Hint": "进度已保存，重新上传同一文件后可点击'继续翻译'恢复",
        "Unfinished Translation Detected": "检测到未完成的翻译，可点击'继续翻译'",
        "API Auth Error": "API Key 无效或已失效，请检查翻译页顶部的 API Key",
        "API Quota Error": "余额/配额不足，请充值或更换 Key",
        "API Keys Exhausted": "所有 API Key 均不可用（无效或配额不足），请更换 Key",
        "Completed Files": "完成 {done}/{total}",
        "Missing Segments": "缺 {count} 段",
        "Segments": "段",
        # Proofread tab
        "Proofread": "校对",
        "Proofread Document": "文档",
        "Refresh List": "刷新列表",
        "Save Edits": "保存修改",
        "Re-export": "重新导出",
        "Original Text": "原文",
        "Translated Text": "译文",
        "Edits saved": "已保存 {count} 行修改。",
        "Row count mismatch": "行数不匹配：应为 {expected} 行，实际 {got} 行，未保存。",
        "No proofread documents": "暂无可校对的文档，请先完成一次翻译（暂不支持 PDF）。",
        "Proofread folder missing": "未找到翻译数据：{name}",
        "Export completed": "重新导出完成",
        "Loaded entries": "已加载 {name} 的 {count} 行"
    },
    # Traditional Chinese
    "zh-Hant": {
        "Source Language": "來源語言",
        "Target Language": "目標語言",
        "Use Online Model": "使用線上模型",
        "Models": "模型",
        "API Key": "API 金鑰",
        "Remember Key": "記住金鑰",
        "Enter your API key here": "在此輸入您的 API 金鑰",
        "Upload File": "上傳檔案 (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "上傳檔案",
        "Download Translated File": "下載翻譯後的檔案",
        "Status Message": "狀態訊息",
        "Translate": "翻譯",
        "Local Network Mode (Restart to Apply)": "區域網路模式（重新啟動後生效）",
        "Max Retries": "最大重試次數",
        "Excel Mode": "有漏翻？嘗試模式2",
        "Word Bilingual": "啟用雙語對照",
        "Excel Bilingual": "Excel 雙語模式",
        "PDF Bilingual": "PDF 雙語模式",
        "Subtitle Bilingual": "雙語字幕",
        "TXT Bilingual": "TXT 雙語對照",
        "MD Bilingual": "Markdown 雙語對照",
        "EPUB Bilingual": "EPUB 雙語對照",
        "HTML Bilingual": "HTML 雙語對照",
        "Continue Translation": "繼續翻譯",
        "Thread Count": "執行緒數量",
        "Stop Translation": "停止翻譯",
        "Stopping": "正在停止...",
        "Glossary": "詞彙表",
        "Add Glossary": "+ 新增詞彙表...",
        "Drop CSV file here": "拖放CSV檔案或點擊瀏覽",
        "Add Custom Language": "+ 新增自訂語言...",
        "New Language Name": "新語言名稱",
        "Language Name Placeholder": "例如：克林貢語",
        "Create Language": "建立",
        # Status messages
        "Extracting text": "正在擷取文字",
        "Removing duplicates": "正在移除重複",
        "Splitting text": "正在拆分文字",
        "Translating content": "正在翻譯內容",
        "Translating": "翻譯中",
        "Checking results": "正在檢查結果",
        "Restoring structure": "正在還原結構",
        "Generating output": "正在產生輸出",
        "Extracting PDF content": "正在提取PDF內容",
        "Generating translated PDF": "正在產生翻譯後的PDF檔案",
        "Translation completed": "翻譯完成",
        "Total tokens used": "本次共消耗tokens",
        "Preparing content": "正在準備內容",
        "Continuing from": "繼續自",
        "Retry": "重試",
        "Security Tips": "安全提示",
        "Security Tips Content": "此功能僅在非區域網路模式下可用。金鑰為個人隱私資料，存在安全風險，請確認後謹慎開啟。",
        "Show API Key": "顯示金鑰",
        "Hide API Key": "隱藏金鑰",
        # Tab labels
        "Settings": "設定",
        "History": "歷史記錄",
        "Interface Language": "介面語言",
        # Translation History
        "Translation History": "翻譯記錄",
        "Refresh Records": "重新整理",
        "Back": "返回",
        "No translation records": "暫無翻譯記錄",
        "Time": "時間",
        "Duration": "耗時",
        "Online": "線上",
        "Offline": "離線",
        "Open Output Folder": "開啟輸出資料夾",
        "Open Log Folder": "開啟日誌資料夾",
        "Status": "狀態",
        "Success": "成功",
        "Failed": "失敗",
        "Stopped": "已停止",
        "Tokens": "Tokens",
        # Glossary editor
        "Edit Glossary": "編輯詞彙表",
        "Load Glossary": "載入詞彙表",
        "Save Glossary": "儲存詞彙表",
        # Settings extras
        "AI Glossary Extraction": "AI 術語擷取",
        "AI Glossary Extraction Info": "翻譯前使用大型模型自動擷取術語",
        "RPM Limit (0 = unlimited, restart to apply)": "RPM 限制（0 為不限制，重新啟動後生效）",
        "Optional Modules": "選用模組",
        # Runtime messages
        "Please select file(s) to translate.": "請選擇要翻譯的檔案。",
        "API key is required for online models.": "使用線上模型需要填寫 API 金鑰。",
        "Translation stopped by user.": "翻譯已被使用者停止。",
        "No supported files found.": "未找到支援的檔案。",
        "Please select a model first": "請先選擇模型。",
        "No Local Model Placeholder": "未偵測到本地模型 — 安裝 Ollama 或在設定中啟用線上模型",
        "Progress Saved Hint": "進度已儲存，重新上傳同一檔案後可點擊'繼續翻譯'恢復",
        "Unfinished Translation Detected": "偵測到未完成的翻譯，可點擊'繼續翻譯'",
        "API Auth Error": "API 金鑰無效或已失效，請檢查翻譯頁頂部的 API 金鑰",
        "API Quota Error": "餘額/配額不足，請儲值或更換金鑰",
        "API Keys Exhausted": "所有 API 金鑰均不可用（無效或配額不足），請更換金鑰",
        "Completed Files": "完成 {done}/{total}",
        "Missing Segments": "缺 {count} 段",
        "Segments": "段",
        # Proofread tab
        "Proofread": "校對",
        "Proofread Document": "文件",
        "Refresh List": "重新整理清單",
        "Save Edits": "儲存修改",
        "Re-export": "重新匯出",
        "Original Text": "原文",
        "Translated Text": "譯文",
        "Edits saved": "已儲存 {count} 列修改。",
        "Row count mismatch": "列數不符：應為 {expected} 列，實際 {got} 列，未儲存。",
        "No proofread documents": "暫無可校對的文件，請先完成一次翻譯（暫不支援 PDF）。",
        "Proofread folder missing": "未找到翻譯資料：{name}",
        "Export completed": "重新匯出完成",
        "Loaded entries": "已載入 {name} 的 {count} 列"
    },
    # Japanese
    "ja": {
        "Source Language": "ソース言語",
        "Target Language": "ターゲット言語",
        "Use Online Model": "オンラインモデルを使用",
        "Models": "モデル",
        "API Key": "APIキー",
        "Remember Key": "キーを記憶",
        "Enter your API key here": "APIキーを入力してください",
        "Upload File": "ファイルをアップロード (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "ファイルをアップロード",
        "Download Translated File": "翻訳ファイルをダウンロード",
        "Status Message": "ステータスメッセージ",
        "Translate": "翻訳",
        "Local Network Mode (Restart to Apply)": "ローカルネットワークモード（再起動後に適用）",
        "Max Retries": "最大再試行回数",
        "Excel Mode": "翻訳漏れ？モード2を試す",
        "Word Bilingual": "二言語対照を有効にする",
        "Excel Bilingual": "Excelバイリンガルモードを有効にする",
        "PDF Bilingual": "PDFバイリンガルモードを有効にする",
        "Subtitle Bilingual": "二言語字幕を有効にする",
        "TXT Bilingual": "TXT二言語対照を有効にする",
        "MD Bilingual": "Markdown二言語対照を有効にする",
        "EPUB Bilingual": "EPUB二言語対照を有効にする",
        "HTML Bilingual": "HTML二言語対照を有効にする",
        "Continue Translation": "翻訳を続ける",
        "Thread Count": "スレッド数",
        "Stop Translation": "翻訳を停止",
        "Stopping": "停止中...",
        "Glossary": "用語集",
        "Add Glossary": "+ 用語集を追加...",
        "Drop CSV file here": "CSVファイルをドロップまたはクリック",
        "Add Custom Language": "+ カスタム言語を追加...",
        "New Language Name": "新しい言語名",
        "Language Name Placeholder": "例：クリンゴン語",
        "Create Language": "作成",
        # Status messages
        "Extracting text": "テキストを抽出中",
        "Removing duplicates": "重複を削除中",
        "Splitting text": "テキストを分割中",
        "Translating content": "コンテンツを翻訳中",
        "Translating": "翻訳中",
        "Checking results": "結果を確認中",
        "Restoring structure": "構造を復元中",
        "Generating output": "出力を生成中",
        "Extracting PDF content": "PDFコンテンツを抽出中",
        "Generating translated PDF": "翻訳済みPDFを生成中",
        "Translation completed": "翻訳完了",
        "Total tokens used": "合計トークン数",
        "Preparing content": "コンテンツを準備中",
        "Continuing from": "から継続",
        "Retry": "再試行",
        "Security Tips": "セキュリティに関するヒント",
        "Security Tips Content": "この機能は非LANモードでのみ使用できます。APIキーは個人のプライバシーデータであり、セキュリティリスクがあります。慎重に有効にしてください。",
        "Show API Key": "キーを表示",
        "Hide API Key": "キーを非表示",
        # Tab labels
        "Settings": "設定",
        "History": "履歴",
        "Interface Language": "表示言語",
        # Translation History
        "Translation History": "翻訳履歴",
        "Refresh Records": "更新",
        "Back": "戻る",
        "No translation records": "翻訳履歴がありません",
        "Time": "時間",
        "Duration": "所要時間",
        "Online": "オンライン",
        "Offline": "オフライン",
        "Open Output Folder": "出力フォルダを開く",
        "Open Log Folder": "ログフォルダを開く",
        "Status": "ステータス",
        "Success": "成功",
        "Failed": "失敗",
        "Stopped": "停止済み",
        "Tokens": "トークン",
        # Glossary editor
        "Edit Glossary": "用語集を編集",
        "Load Glossary": "用語集を読み込む",
        "Save Glossary": "用語集を保存",
        # Settings extras
        "AI Glossary Extraction": "AI用語抽出",
        "AI Glossary Extraction Info": "翻訳前にLLMで用語を抽出します",
        "RPM Limit (0 = unlimited, restart to apply)": "RPM制限（0は無制限、再起動後に適用）",
        "Optional Modules": "オプションモジュール",
        # Runtime messages
        "Please select file(s) to translate.": "翻訳するファイルを選択してください。",
        "API key is required for online models.": "オンラインモデルにはAPIキーが必要です。",
        "Translation stopped by user.": "翻訳はユーザーによって停止されました。",
        "No supported files found.": "サポートされているファイルが見つかりません。",
        "Please select a model first": "先にモデルを選択してください。",
        "No Local Model Placeholder": "ローカルモデルが見つかりません — Ollamaをインストールするか、設定でオンラインモデルを有効にしてください",
        "Progress Saved Hint": "進捗は保存されました。同じファイルを再アップロードして「翻訳を続ける」で再開できます。",
        "Unfinished Translation Detected": "未完了の翻訳が見つかりました。「翻訳を続ける」をクリックできます。",
        "API Auth Error": "APIキーが無効または期限切れです。翻訳タブ上部のAPIキーを確認してください。",
        "API Quota Error": "残高/クォータが不足しています。チャージするかキーを変更してください。",
        "API Keys Exhausted": "すべてのAPIキーが使用できません（無効またはクォータ不足）。キーを変更してください。",
        "Completed Files": "完了 {done}/{total}",
        "Missing Segments": "{count} セグメント欠落",
        "Segments": "セグメント",
        # Proofread tab
        "Proofread": "校正",
        "Proofread Document": "ドキュメント",
        "Refresh List": "リストを更新",
        "Save Edits": "編集を保存",
        "Re-export": "再エクスポート",
        "Original Text": "原文",
        "Translated Text": "訳文",
        "Edits saved": "{count} 行の編集を保存しました。",
        "Row count mismatch": "行数が一致しません：{expected} 行のはずが {got} 行です。保存されませんでした。",
        "No proofread documents": "校正可能なドキュメントがありません。先に翻訳を完了してください（PDFは非対応）。",
        "Proofread folder missing": "翻訳データが見つかりません：{name}",
        "Export completed": "再エクスポートが完了しました",
        "Loaded entries": "{name} から {count} 行を読み込みました"
    },
    # Spanish
    "es": {
        "Source Language": "Idioma de origen",
        "Target Language": "Idioma de destino",
        "Use Online Model": "Usar modelo en línea",
        "Models": "Modelos",
        "API Key": "Clave API",
        "Remember Key": "Recordar clave",
        "Enter your API key here": "Ingrese su clave API aquí",
        "Upload File": "Subir archivo (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "Subir archivos",
        "Download Translated File": "Descargar archivo traducido",
        "Status Message": "Mensaje de estado",
        "Translate": "Traducir",
        "Local Network Mode (Restart to Apply)": "Modo de red local (Reiniciar para aplicar)",
        "Max Retries": "Número máximo de reintentos",
        "Excel Mode": "¿Traducción incompleta? Probar modo 2",
        "Word Bilingual": "Habilitar comparación bilingüe",
        "Excel Bilingual": "Habilitar modo bilingüe de Excel",
        "PDF Bilingual": "Habilitar modo bilingüe de PDF",
        "Continue Translation": "Continuar traducción",
        "Thread Count": "Número de hilos",
        "Stop Translation": "Detener traducción",
        "Stopping": "Deteniendo...",
        "Glossary": "Glosario",
        "Add Glossary": "+ Agregar glosario...",
        "Drop CSV file here": "Suelte el archivo CSV aquí o haga clic",
        "Add Custom Language": "+ Agregar idioma...",
        "New Language Name": "Nombre del nuevo idioma",
        "Language Name Placeholder": "ej. Klingon",
        "Create Language": "Crear",
        # Status messages
        "Extracting text": "Extrayendo texto",
        "Removing duplicates": "Eliminando duplicados",
        "Splitting text": "Dividiendo texto",
        "Translating content": "Traduciendo contenido",
        "Translating": "Traduciendo",
        "Checking results": "Verificando resultados",
        "Restoring structure": "Restaurando estructura",
        "Generating output": "Generando salida",
        "Extracting PDF content": "Extrayendo contenido del PDF",
        "Generating translated PDF": "Generando PDF traducido",
        "Translation completed": "Traducción completada",
        "Total tokens used": "Tokens totales utilizados",
        "Preparing content": "Preparando contenido",
        "Continuing from": "Continuando desde",
        "Retry": "Reintento",
        "Security Tips": "Consejos de seguridad",
        "Security Tips Content": "Esta función solo está disponible en modo no LAN. Las claves API son datos privados con riesgos de seguridad. Por favor, habilite con precaución.",
        "Show API Key": "Mostrar clave",
        "Hide API Key": "Ocultar clave",
        # Translation History
        "Translation History": "Historial de traducción",
        "Refresh Records": "Actualizar",
        "Back": "Volver",
        "No translation records": "No hay registros de traducción",
        "Time": "Tiempo",
        "Duration": "Duración",
        "Online": "En línea",
        "Offline": "Sin conexión",
        "Open Output Folder": "Abrir carpeta de salida",
        "Open Log Folder": "Abrir carpeta de registros",
        "Status": "Estado",
        "Success": "Éxito",
        "Failed": "Fallido",
        "Stopped": "Detenido",
        "Tokens": "Tokens",
        "Interface Language": "Idioma de la interfaz",
        # Bilingual modules
        "Subtitle Bilingual": "Habilitar subtítulos bilingües",
        "TXT Bilingual": "Habilitar modo bilingüe TXT",
        "MD Bilingual": "Habilitar modo bilingüe Markdown",
        "EPUB Bilingual": "Habilitar modo bilingüe EPUB",
        "HTML Bilingual": "Habilitar modo bilingüe HTML",
        # Tab labels
        "Settings": "Configuración",
        "History": "Historial",
        # Glossary editor
        "Edit Glossary": "Editar glosario",
        "Load Glossary": "Cargar glosario",
        "Save Glossary": "Guardar glosario",
        # Settings extras
        "AI Glossary Extraction": "Extracción de glosario con IA",
        "AI Glossary Extraction Info": "Extraer términos con el LLM antes de traducir",
        "RPM Limit (0 = unlimited, restart to apply)": "Límite de RPM (0 = sin límite, reiniciar para aplicar)",
        "Optional Modules": "Módulos opcionales",
        # Runtime messages
        "Please select file(s) to translate.": "Seleccione el/los archivo(s) a traducir.",
        "API key is required for online models.": "Se requiere una clave API para los modelos en línea.",
        "Translation stopped by user.": "Traducción detenida por el usuario.",
        "No supported files found.": "No se encontraron archivos compatibles.",
        "Please select a model first": "Seleccione primero un modelo.",
        "No Local Model Placeholder": "No se detectó ningún modelo local: instale Ollama o active los modelos en línea en Configuración",
        "Progress Saved Hint": "Progreso guardado. Vuelva a subir el mismo archivo y haga clic en 'Continuar traducción' para reanudar.",
        "Unfinished Translation Detected": "Se detectó una traducción sin terminar: puede hacer clic en 'Continuar traducción'.",
        "API Auth Error": "La clave API no es válida o ha caducado. Compruebe la clave API en la parte superior de la pestaña Traducir.",
        "API Quota Error": "Saldo/cuota insuficiente. Recargue o cambie a otra clave.",
        "API Keys Exhausted": "Todas las claves API fallaron (no válidas o sin cuota). Reemplace la(s) clave(s).",
        "Completed Files": "Completado {done}/{total}",
        "Missing Segments": "{count} segmento(s) faltante(s)",
        "Segments": "segmentos",
        # Proofread tab
        "Proofread": "Revisar",
        "Proofread Document": "Documento",
        "Refresh List": "Actualizar lista",
        "Save Edits": "Guardar cambios",
        "Re-export": "Reexportar",
        "Original Text": "Original",
        "Translated Text": "Traducción",
        "Edits saved": "Se guardaron {count} fila(s) editada(s).",
        "Row count mismatch": "Número de filas no coincide: se esperaban {expected}, se obtuvieron {got}. Cambios no guardados.",
        "No proofread documents": "No se encontraron documentos revisables. Complete primero una traducción (PDF no es compatible).",
        "Proofread folder missing": "Datos de traducción no encontrados: {name}",
        "Export completed": "Reexportación completada",
        "Loaded entries": "Se cargaron {count} fila(s) de {name}"
    },
    # French
    "fr": {
        "Source Language": "Langue source",
        "Target Language": "Langue cible",
        "Use Online Model": "Utiliser un modèle en ligne",
        "Models": "Modèles",
        "API Key": "Clé API",
        "Remember Key": "Se souvenir de la clé",
        "Enter your API key here": "Entrez votre clé API ici",
        "Upload File": "Télécharger le fichier (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "Télécharger les fichiers",
        "Download Translated File": "Télécharger le fichier traduit",
        "Status Message": "Message d'état",
        "Translate": "Traduire",
        "Local Network Mode (Restart to Apply)": "Mode réseau local (Redémarrer pour appliquer)",
        "Max Retries": "Nombre maximal de tentatives",
        "Excel Mode": "Traduction incomplète ? Essayez le mode 2",
        "Word Bilingual": "Activer la comparaison bilingue",
        "Excel Bilingual": "Activer le mode bilingue Excel",
        "PDF Bilingual": "Activer le mode bilingue PDF",
        "Continue Translation": "Continuer la traduction",
        "Thread Count": "Nombre de threads",
        "Stop Translation": "Arrêter la traduction",
        "Stopping": "Arrêt en cours...",
        "Glossary": "Glossaire",
        "Add Glossary": "+ Ajouter un glossaire...",
        "Drop CSV file here": "Déposez le fichier CSV ici ou cliquez",
        "Add Custom Language": "+ Ajouter une langue...",
        "New Language Name": "Nom de la nouvelle langue",
        "Language Name Placeholder": "ex. Klingon",
        "Create Language": "Créer",
        # Status messages
        "Extracting text": "Extraction du texte",
        "Removing duplicates": "Suppression des doublons",
        "Splitting text": "Division du texte",
        "Translating content": "Traduction du contenu",
        "Translating": "Traduction",
        "Checking results": "Vérification des résultats",
        "Restoring structure": "Restauration de la structure",
        "Generating output": "Génération de la sortie",
        "Extracting PDF content": "Extraction du contenu PDF",
        "Generating translated PDF": "Génération du PDF traduit",
        "Translation completed": "Traduction terminée",
        "Total tokens used": "Tokens totaux utilisés",
        "Preparing content": "Préparation du contenu",
        "Continuing from": "Continuer depuis",
        "Retry": "Réessayer",
        "Security Tips": "Conseils de sécurité",
        "Security Tips Content": "Cette fonction n'est disponible qu'en mode non-LAN. Les clés API sont des données privées avec des risques de sécurité. Veuillez activer avec prudence.",
        "Show API Key": "Afficher la clé",
        "Hide API Key": "Masquer la clé",
        # Translation History
        "Translation History": "Historique des traductions",
        "Refresh Records": "Actualiser",
        "Back": "Retour",
        "No translation records": "Aucun historique de traduction",
        "Time": "Heure",
        "Duration": "Durée",
        "Online": "En ligne",
        "Offline": "Hors ligne",
        "Open Output Folder": "Ouvrir le dossier de sortie",
        "Open Log Folder": "Ouvrir le dossier des journaux",
        "Status": "Statut",
        "Success": "Succès",
        "Failed": "Échec",
        "Stopped": "Arrêté",
        "Tokens": "Tokens",
        "Interface Language": "Langue de l'interface",
        # Bilingual modules
        "Subtitle Bilingual": "Activer les sous-titres bilingues",
        "TXT Bilingual": "Activer le mode bilingue TXT",
        "MD Bilingual": "Activer le mode bilingue Markdown",
        "EPUB Bilingual": "Activer le mode bilingue EPUB",
        "HTML Bilingual": "Activer le mode bilingue HTML",
        # Tab labels
        "Settings": "Paramètres",
        "History": "Historique",
        # Glossary editor
        "Edit Glossary": "Modifier le glossaire",
        "Load Glossary": "Charger le glossaire",
        "Save Glossary": "Enregistrer le glossaire",
        # Settings extras
        "AI Glossary Extraction": "Extraction de glossaire par IA",
        "AI Glossary Extraction Info": "Extraire les termes avec le LLM avant de traduire",
        "RPM Limit (0 = unlimited, restart to apply)": "Limite RPM (0 = illimité, redémarrer pour appliquer)",
        "Optional Modules": "Modules optionnels",
        # Runtime messages
        "Please select file(s) to translate.": "Veuillez sélectionner le(s) fichier(s) à traduire.",
        "API key is required for online models.": "Une clé API est requise pour les modèles en ligne.",
        "Translation stopped by user.": "Traduction arrêtée par l'utilisateur.",
        "No supported files found.": "Aucun fichier pris en charge trouvé.",
        "Please select a model first": "Veuillez d'abord sélectionner un modèle.",
        "No Local Model Placeholder": "Aucun modèle local détecté — installez Ollama ou activez les modèles en ligne dans les Paramètres",
        "Progress Saved Hint": "Progression enregistrée. Téléchargez à nouveau le même fichier et cliquez sur « Continuer la traduction » pour reprendre.",
        "Unfinished Translation Detected": "Traduction inachevée détectée — vous pouvez cliquer sur « Continuer la traduction ».",
        "API Auth Error": "La clé API est invalide ou expirée. Veuillez vérifier la clé API en haut de l'onglet Traduire.",
        "API Quota Error": "Solde/quota insuffisant. Veuillez recharger ou changer de clé.",
        "API Keys Exhausted": "Toutes les clés API ont échoué (invalides ou quota épuisé). Veuillez remplacer la ou les clés.",
        "Completed Files": "Terminé {done}/{total}",
        "Missing Segments": "{count} segment(s) manquant(s)",
        "Segments": "segments",
        # Proofread tab
        "Proofread": "Relecture",
        "Proofread Document": "Document",
        "Refresh List": "Actualiser la liste",
        "Save Edits": "Enregistrer les modifications",
        "Re-export": "Réexporter",
        "Original Text": "Original",
        "Translated Text": "Traduction",
        "Edits saved": "{count} ligne(s) modifiée(s) enregistrée(s).",
        "Row count mismatch": "Nombre de lignes incorrect : {expected} attendues, {got} obtenues. Modifications non enregistrées.",
        "No proofread documents": "Aucun document relisible trouvé. Terminez d'abord une traduction (PDF non pris en charge).",
        "Proofread folder missing": "Données de traduction introuvables : {name}",
        "Export completed": "Réexportation terminée",
        "Loaded entries": "{count} ligne(s) chargée(s) depuis {name}"
    },
    # German
    "de": {
        "Source Language": "Ausgangssprache",
        "Target Language": "Zielsprache",
        "Use Online Model": "Online-Modell verwenden",
        "Models": "Modelle",
        "API Key": "API-Schlüssel",
        "Remember Key": "Schlüssel merken",
        "Enter your API key here": "Geben Sie hier Ihren API-Schlüssel ein",
        "Upload File": "Datei hochladen (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "Dateien hochladen",
        "Download Translated File": "Übersetzte Datei herunterladen",
        "Status Message": "Statusnachricht",
        "Translate": "Übersetzen",
        "Local Network Mode (Restart to Apply)": "Lokaler Netzwerkmodus (Neustart erforderlich)",
        "Max Retries": "Maximale Wiederholungsversuche",
        "Excel Mode": "Übersetzung unvollständig? Versuchen Sie Modus 2",
        "Word Bilingual": "Zweisprachigen Vergleich aktivieren",
        "Excel Bilingual": "Excel-Zweisprachenmodus aktivieren",
        "PDF Bilingual": "PDF-Zweisprachenmodus aktivieren",
        "Continue Translation": "Übersetzung fortsetzen",
        "Thread Count": "Thread-Anzahl",
        "Stop Translation": "Übersetzung stoppen",
        "Stopping": "Stoppe...",
        "Glossary": "Glossar",
        "Add Glossary": "+ Glossar hinzufügen...",
        "Drop CSV file here": "CSV-Datei hier ablegen oder klicken",
        "Add Custom Language": "+ Sprache hinzufügen...",
        "New Language Name": "Name der neuen Sprache",
        "Language Name Placeholder": "z.B. Klingonisch",
        "Create Language": "Erstellen",
        # Status messages
        "Extracting text": "Text extrahieren",
        "Removing duplicates": "Duplikate entfernen",
        "Splitting text": "Text aufteilen",
        "Translating content": "Inhalt übersetzen",
        "Translating": "Übersetze",
        "Checking results": "Ergebnisse prüfen",
        "Restoring structure": "Struktur wiederherstellen",
        "Generating output": "Ausgabe generieren",
        "Extracting PDF content": "PDF-Inhalt extrahieren",
        "Generating translated PDF": "Übersetztes PDF generieren",
        "Translation completed": "Übersetzung abgeschlossen",
        "Total tokens used": "Verwendete Tokens gesamt",
        "Preparing content": "Inhalt vorbereiten",
        "Continuing from": "Fortsetzen von",
        "Retry": "Wiederholen",
        "Security Tips": "Sicherheitshinweise",
        "Security Tips Content": "Diese Funktion ist nur im Nicht-LAN-Modus verfügbar. API-Schlüssel sind private Daten mit Sicherheitsrisiken. Bitte mit Vorsicht aktivieren.",
        "Show API Key": "Schlüssel anzeigen",
        "Hide API Key": "Schlüssel verbergen",
        # Translation History
        "Translation History": "Übersetzungsverlauf",
        "Refresh Records": "Aktualisieren",
        "Back": "Zurück",
        "No translation records": "Keine Übersetzungseinträge",
        "Time": "Zeit",
        "Duration": "Dauer",
        "Online": "Online",
        "Offline": "Offline",
        "Open Output Folder": "Ausgabeordner öffnen",
        "Open Log Folder": "Protokollordner öffnen",
        "Status": "Status",
        "Success": "Erfolg",
        "Failed": "Fehlgeschlagen",
        "Stopped": "Gestoppt",
        "Tokens": "Tokens",
        "Interface Language": "Oberflächensprache",
        # Bilingual modules
        "Subtitle Bilingual": "Zweisprachige Untertitel aktivieren",
        "TXT Bilingual": "TXT-Zweisprachenmodus aktivieren",
        "MD Bilingual": "Markdown-Zweisprachenmodus aktivieren",
        "EPUB Bilingual": "EPUB-Zweisprachenmodus aktivieren",
        "HTML Bilingual": "HTML-Zweisprachenmodus aktivieren",
        # Tab labels
        "Settings": "Einstellungen",
        "History": "Verlauf",
        # Glossary editor
        "Edit Glossary": "Glossar bearbeiten",
        "Load Glossary": "Glossar laden",
        "Save Glossary": "Glossar speichern",
        # Settings extras
        "AI Glossary Extraction": "KI-Glossarextraktion",
        "AI Glossary Extraction Info": "Begriffe vor der Übersetzung mit dem LLM extrahieren",
        "RPM Limit (0 = unlimited, restart to apply)": "RPM-Limit (0 = unbegrenzt, Neustart erforderlich)",
        "Optional Modules": "Optionale Module",
        # Runtime messages
        "Please select file(s) to translate.": "Bitte wählen Sie die zu übersetzenden Datei(en) aus.",
        "API key is required for online models.": "Für Online-Modelle ist ein API-Schlüssel erforderlich.",
        "Translation stopped by user.": "Übersetzung vom Benutzer gestoppt.",
        "No supported files found.": "Keine unterstützten Dateien gefunden.",
        "Please select a model first": "Bitte wählen Sie zuerst ein Modell aus.",
        "No Local Model Placeholder": "Kein lokales Modell erkannt — installieren Sie Ollama oder aktivieren Sie Online-Modelle in den Einstellungen",
        "Progress Saved Hint": "Fortschritt gespeichert. Laden Sie dieselbe Datei erneut hoch und klicken Sie auf „Übersetzung fortsetzen“, um fortzufahren.",
        "Unfinished Translation Detected": "Unvollständige Übersetzung erkannt — Sie können auf „Übersetzung fortsetzen“ klicken.",
        "API Auth Error": "Der API-Schlüssel ist ungültig oder abgelaufen. Bitte überprüfen Sie den API-Schlüssel oben im Tab „Übersetzen“.",
        "API Quota Error": "Unzureichendes Guthaben/Kontingent. Bitte aufladen oder zu einem anderen Schlüssel wechseln.",
        "API Keys Exhausted": "Alle API-Schlüssel sind fehlgeschlagen (ungültig oder Kontingent erschöpft). Bitte ersetzen Sie die Schlüssel.",
        "Completed Files": "Abgeschlossen {done}/{total}",
        "Missing Segments": "{count} Segment(e) fehlen",
        "Segments": "Segmente",
        # Proofread tab
        "Proofread": "Korrektur",
        "Proofread Document": "Dokument",
        "Refresh List": "Liste aktualisieren",
        "Save Edits": "Änderungen speichern",
        "Re-export": "Erneut exportieren",
        "Original Text": "Original",
        "Translated Text": "Übersetzung",
        "Edits saved": "{count} bearbeitete Zeile(n) gespeichert.",
        "Row count mismatch": "Zeilenanzahl stimmt nicht überein: erwartet {expected}, erhalten {got}. Änderungen nicht gespeichert.",
        "No proofread documents": "Keine korrigierbaren Dokumente gefunden. Schließen Sie zuerst eine Übersetzung ab (PDF wird nicht unterstützt).",
        "Proofread folder missing": "Übersetzungsdaten nicht gefunden: {name}",
        "Export completed": "Erneuter Export abgeschlossen",
        "Loaded entries": "{count} Zeile(n) aus {name} geladen"
    },
    # Italian
    "it": {
        "Source Language": "Lingua di origine",
        "Target Language": "Lingua di destinazione",
        "Use Online Model": "Usa modello online",
        "Models": "Modelli",
        "API Key": "Chiave API",
        "Remember Key": "Ricorda chiave",
        "Enter your API key here": "Inserisci qui la tua chiave API",
        "Upload File": "Carica file (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "Carica file",
        "Download Translated File": "Scarica file tradotto",
        "Status Message": "Messaggio di stato",
        "Translate": "Traduci",
        "Local Network Mode (Restart to Apply)": "Modalità rete locale (Riavvia per applicare)",
        "Max Retries": "Numero massimo di tentativi",
        "Excel Mode": "Traduzione incompleta? Prova la modalità 2",
        "Word Bilingual": "Abilita confronto bilingue",
        "Excel Bilingual": "Abilita modalità bilingue Excel",
        "PDF Bilingual": "Abilita modalità bilingue PDF",
        "Continue Translation": "Continua traduzione",
        "Thread Count": "Numero di thread",
        "Stop Translation": "Interrompi traduzione",
        "Stopping": "Interruzione in corso...",
        "Glossary": "Glossario",
        "Add Glossary": "+ Aggiungi glossario...",
        "Drop CSV file here": "Trascina il file CSV qui o clicca",
        "Add Custom Language": "+ Aggiungi lingua...",
        "New Language Name": "Nome della nuova lingua",
        "Language Name Placeholder": "es. Klingon",
        "Create Language": "Crea",
        # Status messages
        "Extracting text": "Estrazione del testo",
        "Removing duplicates": "Rimozione dei duplicati",
        "Splitting text": "Divisione del testo",
        "Translating content": "Traduzione del contenuto",
        "Translating": "Traduzione",
        "Checking results": "Verifica dei risultati",
        "Restoring structure": "Ripristino della struttura",
        "Generating output": "Generazione dell'output",
        "Extracting PDF content": "Estrazione del contenuto PDF",
        "Generating translated PDF": "Generazione del PDF tradotto",
        "Translation completed": "Traduzione completata",
        "Total tokens used": "Token totali utilizzati",
        "Preparing content": "Preparazione del contenuto",
        "Continuing from": "Continua da",
        "Retry": "Riprova",
        "Security Tips": "Suggerimenti per la sicurezza",
        "Security Tips Content": "Questa funzione è disponibile solo in modalità non-LAN. Le chiavi API sono dati privati con rischi per la sicurezza. Si prega di abilitare con cautela.",
        "Show API Key": "Mostra chiave",
        "Hide API Key": "Nascondi chiave",
        # Translation History
        "Translation History": "Cronologia traduzioni",
        "Refresh Records": "Aggiorna",
        "Back": "Indietro",
        "No translation records": "Nessun record di traduzione",
        "Time": "Ora",
        "Duration": "Durata",
        "Online": "Online",
        "Offline": "Offline",
        "Open Output Folder": "Apri cartella di output",
        "Open Log Folder": "Apri cartella dei log",
        "Status": "Stato",
        "Success": "Successo",
        "Failed": "Fallito",
        "Stopped": "Interrotto",
        "Tokens": "Token",
        "Interface Language": "Lingua dell'interfaccia",
        # Bilingual modules
        "Subtitle Bilingual": "Abilita sottotitoli bilingue",
        "TXT Bilingual": "Abilita modalità bilingue TXT",
        "MD Bilingual": "Abilita modalità bilingue Markdown",
        "EPUB Bilingual": "Abilita modalità bilingue EPUB",
        "HTML Bilingual": "Abilita modalità bilingue HTML",
        # Tab labels
        "Settings": "Impostazioni",
        "History": "Cronologia",
        # Glossary editor
        "Edit Glossary": "Modifica glossario",
        "Load Glossary": "Carica glossario",
        "Save Glossary": "Salva glossario",
        # Settings extras
        "AI Glossary Extraction": "Estrazione glossario con IA",
        "AI Glossary Extraction Info": "Estrai i termini con l'LLM prima di tradurre",
        "RPM Limit (0 = unlimited, restart to apply)": "Limite RPM (0 = illimitato, riavviare per applicare)",
        "Optional Modules": "Moduli opzionali",
        # Runtime messages
        "Please select file(s) to translate.": "Seleziona il/i file da tradurre.",
        "API key is required for online models.": "È necessaria una chiave API per i modelli online.",
        "Translation stopped by user.": "Traduzione interrotta dall'utente.",
        "No supported files found.": "Nessun file supportato trovato.",
        "Please select a model first": "Seleziona prima un modello.",
        "No Local Model Placeholder": "Nessun modello locale rilevato — installa Ollama o abilita i modelli online nelle Impostazioni",
        "Progress Saved Hint": "Avanzamento salvato. Ricarica lo stesso file e fai clic su \"Continua traduzione\" per riprendere.",
        "Unfinished Translation Detected": "Rilevata traduzione incompleta — puoi fare clic su \"Continua traduzione\".",
        "API Auth Error": "La chiave API non è valida o è scaduta. Controlla la chiave API in alto nella scheda Traduci.",
        "API Quota Error": "Saldo/quota insufficiente. Ricarica o passa a un'altra chiave.",
        "API Keys Exhausted": "Tutte le chiavi API hanno fallito (non valide o quota esaurita). Sostituisci la/le chiave/i.",
        "Completed Files": "Completato {done}/{total}",
        "Missing Segments": "{count} segmento/i mancante/i",
        "Segments": "segmenti",
        # Proofread tab
        "Proofread": "Revisione",
        "Proofread Document": "Documento",
        "Refresh List": "Aggiorna elenco",
        "Save Edits": "Salva modifiche",
        "Re-export": "Riesporta",
        "Original Text": "Originale",
        "Translated Text": "Traduzione",
        "Edits saved": "Salvate {count} riga/righe modificata/e.",
        "Row count mismatch": "Numero di righe non corrispondente: previste {expected}, ottenute {got}. Modifiche non salvate.",
        "No proofread documents": "Nessun documento revisionabile trovato. Completa prima una traduzione (PDF non supportato).",
        "Proofread folder missing": "Dati di traduzione non trovati: {name}",
        "Export completed": "Riesportazione completata",
        "Loaded entries": "Caricate {count} riga/righe da {name}"
    },
    # Portuguese
    "pt": {
        "Source Language": "Idioma de origem",
        "Target Language": "Idioma de destino",
        "Use Online Model": "Usar modelo online",
        "Models": "Modelos",
        "API Key": "Chave de API",
        "Remember Key": "Lembrar chave",
        "Enter your API key here": "Digite sua chave de API aqui",
        "Upload File": "Enviar arquivo (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "Enviar arquivos",
        "Download Translated File": "Baixar arquivo traduzido",
        "Status Message": "Mensagem de status",
        "Translate": "Traduzir",
        "Local Network Mode (Restart to Apply)": "Modo de rede local (Reiniciar para aplicar)",
        "Max Retries": "Número máximo de tentativas",
        "Excel Mode": "Tradução incompleta? Tente o modo 2",
        "Word Bilingual": "Ativar comparação bilíngue",
        "Excel Bilingual": "Ativar modo bilíngue Excel",
        "PDF Bilingual": "Ativar modo bilíngue PDF",
        "Continue Translation": "Continuar tradução",
        "Thread Count": "Número de threads",
        "Stop Translation": "Parar tradução",
        "Stopping": "Parando...",
        "Glossary": "Glossário",
        "Add Glossary": "+ Adicionar glossário...",
        "Drop CSV file here": "Solte o arquivo CSV aqui ou clique",
        "Add Custom Language": "+ Adicionar idioma...",
        "New Language Name": "Nome do novo idioma",
        "Language Name Placeholder": "ex. Klingon",
        "Create Language": "Criar",
        # Status messages
        "Extracting text": "Extraindo texto",
        "Removing duplicates": "Removendo duplicatas",
        "Splitting text": "Dividindo texto",
        "Translating content": "Traduzindo conteúdo",
        "Translating": "Traduzindo",
        "Checking results": "Verificando resultados",
        "Restoring structure": "Restaurando estrutura",
        "Generating output": "Gerando saída",
        "Extracting PDF content": "Extraindo conteúdo do PDF",
        "Generating translated PDF": "Gerando PDF traduzido",
        "Translation completed": "Tradução concluída",
        "Total tokens used": "Tokens totais utilizados",
        "Preparing content": "Preparando conteúdo",
        "Continuing from": "Continuando de",
        "Retry": "Tentar novamente",
        "Security Tips": "Dicas de segurança",
        "Security Tips Content": "Este recurso está disponível apenas no modo não-LAN. As chaves de API são dados privados com riscos de segurança. Por favor, habilite com cautela.",
        "Show API Key": "Mostrar chave",
        "Hide API Key": "Ocultar chave",
        # Translation History
        "Translation History": "Histórico de traduções",
        "Refresh Records": "Atualizar",
        "Back": "Voltar",
        "No translation records": "Nenhum registro de tradução",
        "Time": "Hora",
        "Duration": "Duração",
        "Online": "Online",
        "Offline": "Offline",
        "Open Output Folder": "Abrir pasta de saída",
        "Open Log Folder": "Abrir pasta de logs",
        "Status": "Status",
        "Success": "Sucesso",
        "Failed": "Falhou",
        "Stopped": "Parado",
        "Tokens": "Tokens",
        "Interface Language": "Idioma da interface",
        # Bilingual modules
        "Subtitle Bilingual": "Ativar legendas bilíngues",
        "TXT Bilingual": "Ativar modo bilíngue TXT",
        "MD Bilingual": "Ativar modo bilíngue Markdown",
        "EPUB Bilingual": "Ativar modo bilíngue EPUB",
        "HTML Bilingual": "Ativar modo bilíngue HTML",
        # Tab labels
        "Settings": "Configurações",
        "History": "Histórico",
        # Glossary editor
        "Edit Glossary": "Editar glossário",
        "Load Glossary": "Carregar glossário",
        "Save Glossary": "Salvar glossário",
        # Settings extras
        "AI Glossary Extraction": "Extração de glossário por IA",
        "AI Glossary Extraction Info": "Extrair termos com o LLM antes de traduzir",
        "RPM Limit (0 = unlimited, restart to apply)": "Limite de RPM (0 = ilimitado, reiniciar para aplicar)",
        "Optional Modules": "Módulos opcionais",
        # Runtime messages
        "Please select file(s) to translate.": "Selecione o(s) arquivo(s) a traduzir.",
        "API key is required for online models.": "É necessária uma chave de API para modelos online.",
        "Translation stopped by user.": "Tradução interrompida pelo usuário.",
        "No supported files found.": "Nenhum arquivo compatível encontrado.",
        "Please select a model first": "Selecione primeiro um modelo.",
        "No Local Model Placeholder": "Nenhum modelo local detectado — instale o Ollama ou ative modelos online nas Configurações",
        "Progress Saved Hint": "Progresso salvo. Envie novamente o mesmo arquivo e clique em \"Continuar tradução\" para retomar.",
        "Unfinished Translation Detected": "Tradução incompleta detectada — você pode clicar em \"Continuar tradução\".",
        "API Auth Error": "A chave de API é inválida ou expirou. Verifique a chave de API no topo da aba Traduzir.",
        "API Quota Error": "Saldo/cota insuficiente. Recarregue ou troque para outra chave.",
        "API Keys Exhausted": "Todas as chaves de API falharam (inválidas ou sem cota). Substitua a(s) chave(s).",
        "Completed Files": "Concluído {done}/{total}",
        "Missing Segments": "{count} segmento(s) ausente(s)",
        "Segments": "segmentos",
        # Proofread tab
        "Proofread": "Revisão",
        "Proofread Document": "Documento",
        "Refresh List": "Atualizar lista",
        "Save Edits": "Salvar edições",
        "Re-export": "Reexportar",
        "Original Text": "Original",
        "Translated Text": "Tradução",
        "Edits saved": "{count} linha(s) editada(s) salva(s).",
        "Row count mismatch": "Número de linhas incompatível: esperado {expected}, obtido {got}. Edições não salvas.",
        "No proofread documents": "Nenhum documento revisável encontrado. Conclua primeiro uma tradução (PDF não é compatível).",
        "Proofread folder missing": "Dados de tradução não encontrados: {name}",
        "Export completed": "Reexportação concluída",
        "Loaded entries": "{count} linha(s) carregada(s) de {name}"
    },
    # Russian
    "ru": {
        "Source Language": "Исходный язык",
        "Target Language": "Целевой язык",
        "Use Online Model": "Использовать онлайн-модель",
        "Models": "Модели",
        "API Key": "API-ключ",
        "Remember Key": "Запомнить ключ",
        "Enter your API key here": "Введите ваш API-ключ здесь",
        "Upload File": "Загрузить файл (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "Загрузить файлы",
        "Download Translated File": "Скачать переведенный файл",
        "Status Message": "Статусное сообщение",
        "Translate": "Перевести",
        "Local Network Mode (Restart to Apply)": "Режим локальной сети (Перезагрузка для применения)",
        "Max Retries": "Максимальное количество повторных попыток",
        "Excel Mode": "Перевод неполный? Попробуйте режим 2",
        "Word Bilingual": "Включить двуязычное сравнение",
        "Excel Bilingual": "Включить двуязычный режим Excel",
        "PDF Bilingual": "Включить двуязычный режим PDF",
        "Continue Translation": "Продолжить перевод",
        "Thread Count": "Количество потоков",
        "Stop Translation": "Остановить перевод",
        "Stopping": "Остановка...",
        "Glossary": "Глоссарий",
        "Add Glossary": "+ Добавить глоссарий...",
        "Drop CSV file here": "Перетащите CSV файл сюда или нажмите",
        "Add Custom Language": "+ Добавить язык...",
        "New Language Name": "Название нового языка",
        "Language Name Placeholder": "напр. Клингонский",
        "Create Language": "Создать",
        # Status messages
        "Extracting text": "Извлечение текста",
        "Removing duplicates": "Удаление дубликатов",
        "Splitting text": "Разделение текста",
        "Translating content": "Перевод содержимого",
        "Translating": "Перевод",
        "Checking results": "Проверка результатов",
        "Restoring structure": "Восстановление структуры",
        "Generating output": "Генерация вывода",
        "Extracting PDF content": "Извлечение содержимого PDF",
        "Generating translated PDF": "Генерация переведённого PDF",
        "Translation completed": "Перевод завершён",
        "Total tokens used": "Всего использовано токенов",
        "Preparing content": "Подготовка содержимого",
        "Continuing from": "Продолжить с",
        "Retry": "Повторить",
        "Security Tips": "Советы по безопасности",
        "Security Tips Content": "Эта функция доступна только в режиме без LAN. API-ключи — это личные данные с рисками безопасности. Пожалуйста, включайте с осторожностью.",
        "Show API Key": "Показать ключ",
        "Hide API Key": "Скрыть ключ",
        # Translation History
        "Translation History": "История переводов",
        "Refresh Records": "Обновить",
        "Back": "Назад",
        "No translation records": "Нет записей о переводах",
        "Time": "Время",
        "Duration": "Длительность",
        "Online": "Онлайн",
        "Offline": "Офлайн",
        "Open Output Folder": "Открыть папку вывода",
        "Open Log Folder": "Открыть папку журналов",
        "Status": "Статус",
        "Success": "Успешно",
        "Failed": "Ошибка",
        "Stopped": "Остановлено",
        "Tokens": "Токены",
        "Interface Language": "Язык интерфейса",
        # Bilingual modules
        "Subtitle Bilingual": "Включить двуязычные субтитры",
        "TXT Bilingual": "Включить двуязычный режим TXT",
        "MD Bilingual": "Включить двуязычный режим Markdown",
        "EPUB Bilingual": "Включить двуязычный режим EPUB",
        "HTML Bilingual": "Включить двуязычный режим HTML",
        # Tab labels
        "Settings": "Настройки",
        "History": "История",
        # Glossary editor
        "Edit Glossary": "Редактировать глоссарий",
        "Load Glossary": "Загрузить глоссарий",
        "Save Glossary": "Сохранить глоссарий",
        # Settings extras
        "AI Glossary Extraction": "Извлечение глоссария ИИ",
        "AI Glossary Extraction Info": "Извлекать термины с помощью LLM перед переводом",
        "RPM Limit (0 = unlimited, restart to apply)": "Лимит RPM (0 — без ограничения, перезапуск для применения)",
        "Optional Modules": "Дополнительные модули",
        # Runtime messages
        "Please select file(s) to translate.": "Пожалуйста, выберите файл(ы) для перевода.",
        "API key is required for online models.": "Для онлайн-моделей требуется API-ключ.",
        "Translation stopped by user.": "Перевод остановлен пользователем.",
        "No supported files found.": "Поддерживаемые файлы не найдены.",
        "Please select a model first": "Сначала выберите модель.",
        "No Local Model Placeholder": "Локальная модель не обнаружена — установите Ollama или включите онлайн-модели в Настройках",
        "Progress Saved Hint": "Прогресс сохранён. Повторно загрузите тот же файл и нажмите «Продолжить перевод», чтобы возобновить.",
        "Unfinished Translation Detected": "Обнаружен незавершённый перевод — вы можете нажать «Продолжить перевод».",
        "API Auth Error": "API-ключ недействителен или истёк. Проверьте API-ключ вверху вкладки «Перевести».",
        "API Quota Error": "Недостаточно средств/квоты. Пополните счёт или смените ключ.",
        "API Keys Exhausted": "Все API-ключи недоступны (недействительны или исчерпана квота). Замените ключ(и).",
        "Completed Files": "Завершено {done}/{total}",
        "Missing Segments": "Пропущено сегментов: {count}",
        "Segments": "сегменты",
        # Proofread tab
        "Proofread": "Корректура",
        "Proofread Document": "Документ",
        "Refresh List": "Обновить список",
        "Save Edits": "Сохранить изменения",
        "Re-export": "Повторный экспорт",
        "Original Text": "Оригинал",
        "Translated Text": "Перевод",
        "Edits saved": "Сохранено изменённых строк: {count}.",
        "Row count mismatch": "Несоответствие количества строк: ожидалось {expected}, получено {got}. Изменения не сохранены.",
        "No proofread documents": "Документы для корректуры не найдены. Сначала завершите перевод (PDF не поддерживается).",
        "Proofread folder missing": "Данные перевода не найдены: {name}",
        "Export completed": "Повторный экспорт завершён",
        "Loaded entries": "Загружено строк из {name}: {count}"
    },
    # Korean
    "ko": {
        "Source Language": "소스 언어",
        "Target Language": "대상 언어",
        "Use Online Model": "온라인 모델 사용",
        "Models": "모델",
        "API Key": "API 키",
        "Remember Key": "키 기억하기",
        "Enter your API key here": "여기에 API 키를 입력하세요",
        "Upload File": "파일 업로드 (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "파일 업로드",
        "Download Translated File": "번역된 파일 다운로드",
        "Status Message": "상태 메시지",
        "Translate": "번역",
        "Local Network Mode (Restart to Apply)": "로컬 네트워크 모드 (적용하려면 재시작)",
        "Max Retries": "최대 재시도 횟수",
        "Excel Mode": "번역이 누락되었나요? 모드 2 시도",
        "Word Bilingual": "이중 언어 비교 활성화",
        "Excel Bilingual": "Excel 이중 언어 모드 활성화",
        "PDF Bilingual": "PDF 이중 언어 모드 활성화",
        "Continue Translation": "번역 계속하기",
        "Thread Count": "스레드 수",
        "Stop Translation": "번역 중지",
        "Stopping": "중지 중...",
        "Glossary": "용어집",
        "Add Glossary": "+ 용어집 추가...",
        "Drop CSV file here": "CSV 파일을 여기에 놓거나 클릭",
        "Add Custom Language": "+ 언어 추가...",
        "New Language Name": "새 언어 이름",
        "Language Name Placeholder": "예: 클링온어",
        "Create Language": "생성",
        # Status messages
        "Extracting text": "텍스트 추출 중",
        "Removing duplicates": "중복 제거 중",
        "Splitting text": "텍스트 분할 중",
        "Translating content": "콘텐츠 번역 중",
        "Translating": "번역 중",
        "Checking results": "결과 확인 중",
        "Restoring structure": "구조 복원 중",
        "Generating output": "출력 생성 중",
        "Extracting PDF content": "PDF 콘텐츠 추출 중",
        "Generating translated PDF": "번역된 PDF 생성 중",
        "Translation completed": "번역 완료",
        "Total tokens used": "총 사용 토큰",
        "Preparing content": "콘텐츠 준비 중",
        "Continuing from": "에서 계속",
        "Retry": "재시도",
        "Security Tips": "보안 팁",
        "Security Tips Content": "이 기능은 비LAN 모드에서만 사용할 수 있습니다. API 키는 보안 위험이 있는 개인 데이터입니다. 신중하게 활성화하십시오.",
        "Show API Key": "키 표시",
        "Hide API Key": "키 숨기기",
        # Translation History
        "Translation History": "번역 기록",
        "Refresh Records": "새로고침",
        "Back": "뒤로",
        "No translation records": "번역 기록이 없습니다",
        "Time": "시간",
        "Duration": "소요 시간",
        "Online": "온라인",
        "Offline": "오프라인",
        "Open Output Folder": "출력 폴더 열기",
        "Open Log Folder": "로그 폴더 열기",
        "Status": "상태",
        "Success": "성공",
        "Failed": "실패",
        "Stopped": "중지됨",
        "Tokens": "토큰",
        "Interface Language": "인터페이스 언어",
        # Bilingual modules
        "Subtitle Bilingual": "이중 언어 자막 활성화",
        "TXT Bilingual": "TXT 이중 언어 모드 활성화",
        "MD Bilingual": "Markdown 이중 언어 모드 활성화",
        "EPUB Bilingual": "EPUB 이중 언어 모드 활성화",
        "HTML Bilingual": "HTML 이중 언어 모드 활성화",
        # Tab labels
        "Settings": "설정",
        "History": "기록",
        # Glossary editor
        "Edit Glossary": "용어집 편집",
        "Load Glossary": "용어집 불러오기",
        "Save Glossary": "용어집 저장",
        # Settings extras
        "AI Glossary Extraction": "AI 용어 추출",
        "AI Glossary Extraction Info": "번역 전에 LLM으로 용어를 추출합니다",
        "RPM Limit (0 = unlimited, restart to apply)": "RPM 제한 (0 = 무제한, 적용하려면 재시작)",
        "Optional Modules": "선택 모듈",
        # Runtime messages
        "Please select file(s) to translate.": "번역할 파일을 선택하세요.",
        "API key is required for online models.": "온라인 모델에는 API 키가 필요합니다.",
        "Translation stopped by user.": "사용자가 번역을 중지했습니다.",
        "No supported files found.": "지원되는 파일을 찾을 수 없습니다.",
        "Please select a model first": "먼저 모델을 선택하세요.",
        "No Local Model Placeholder": "로컬 모델이 감지되지 않음 — Ollama를 설치하거나 설정에서 온라인 모델을 활성화하세요",
        "Progress Saved Hint": "진행 상황이 저장되었습니다. 같은 파일을 다시 업로드하고 '번역 계속하기'를 클릭하여 재개하세요.",
        "Unfinished Translation Detected": "완료되지 않은 번역이 감지되었습니다 — '번역 계속하기'를 클릭할 수 있습니다.",
        "API Auth Error": "API 키가 유효하지 않거나 만료되었습니다. 번역 탭 상단의 API 키를 확인하세요.",
        "API Quota Error": "잔액/할당량이 부족합니다. 충전하거나 다른 키로 전환하세요.",
        "API Keys Exhausted": "모든 API 키가 실패했습니다(무효하거나 할당량 소진). 키를 교체하세요.",
        "Completed Files": "완료 {done}/{total}",
        "Missing Segments": "{count}개 세그먼트 누락",
        "Segments": "세그먼트",
        # Proofread tab
        "Proofread": "교정",
        "Proofread Document": "문서",
        "Refresh List": "목록 새로고침",
        "Save Edits": "수정 저장",
        "Re-export": "다시 내보내기",
        "Original Text": "원문",
        "Translated Text": "번역문",
        "Edits saved": "{count}개 행의 수정을 저장했습니다.",
        "Row count mismatch": "행 수 불일치: {expected}개 예상, {got}개 발견. 저장되지 않았습니다.",
        "No proofread documents": "교정 가능한 문서가 없습니다. 먼저 번역을 완료하세요(PDF는 지원되지 않음).",
        "Proofread folder missing": "번역 데이터를 찾을 수 없습니다: {name}",
        "Export completed": "다시 내보내기 완료",
        "Loaded entries": "{name}에서 {count}개 행을 불러왔습니다"
    },
    # Thai
    "th": {
        "Source Language": "ภาษาต้นฉบับ",
        "Target Language": "ภาษาเป้าหมาย",
        "Use Online Model": "ใช้โมเดลออนไลน์",
        "Models": "โมเดล",
        "API Key": "คีย์ API",
        "Remember Key": "จำคีย์",
        "Enter your API key here": "ป้อนคีย์ API ของคุณที่นี่",
        "Upload File": "อัปโหลดไฟล์ (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "อัปโหลดไฟล์",
        "Download Translated File": "ดาวน์โหลดไฟล์ที่แปลแล้ว",
        "Status Message": "ข้อความสถานะ",
        "Translate": "แปล",
        "Local Network Mode (Restart to Apply)": "โหมดเครือข่ายท้องถิ่น (รีสตาร์ทเพื่อใช้งาน)",
        "Max Retries": "จำนวนการลองซ้ำสูงสุด",
        "Excel Mode": "การแปลขาดหายไป? ลองโหมด 2",
        "Word Bilingual": "เปิดใช้งานการเปรียบเทียบสองภาษา",
        "Excel Bilingual": "เปิดใช้งานโหมดสองภาษา Excel",
        "PDF Bilingual": "เปิดใช้งานโหมดสองภาษา PDF",
        "Continue Translation": "แปลต่อ",
        "Thread Count": "จำนวนเธรด",
        "Stop Translation": "หยุดการแปล",
        "Stopping": "กำลังหยุด...",
        "Glossary": "อภิธานศัพท์",
        "Add Glossary": "+ เพิ่มอภิธานศัพท์...",
        "Drop CSV file here": "วางไฟล์ CSV ที่นี่หรือคลิก",
        "Add Custom Language": "+ เพิ่มภาษา...",
        "New Language Name": "ชื่อภาษาใหม่",
        "Language Name Placeholder": "เช่น คลิงออน",
        "Create Language": "สร้าง",
        # Status messages
        "Extracting text": "กำลังดึงข้อความ",
        "Removing duplicates": "กำลังลบข้อความซ้ำ",
        "Splitting text": "กำลังแบ่งข้อความ",
        "Translating content": "กำลังแปลเนื้อหา",
        "Translating": "กำลังแปล",
        "Checking results": "กำลังตรวจสอบผลลัพธ์",
        "Restoring structure": "กำลังกู้คืนโครงสร้าง",
        "Generating output": "กำลังสร้างผลลัพธ์",
        "Extracting PDF content": "กำลังแยกเนื้อหา PDF",
        "Generating translated PDF": "กำลังสร้างไฟล์ PDF ที่แปลแล้ว",
        "Translation completed": "การแปลเสร็จสมบูรณ์",
        "Total tokens used": "โทเค็นทั้งหมดที่ใช้",
        "Preparing content": "กำลังเตรียมเนื้อหา",
        "Continuing from": "ดำเนินการต่อจาก",
        "Retry": "ลองใหม่",
        "Security Tips": "เคล็ดลับความปลอดภัย",
        "Security Tips Content": "ฟังก์ชันนี้ใช้ได้เฉพาะในโหมดที่ไม่ใช่ LAN คีย์ API เป็นข้อมูลส่วนตัวที่มีความเสี่ยงด้านความปลอดภัย กรุณาเปิดใช้งานด้วยความระมัดระวัง",
        "Show API Key": "แสดงคีย์",
        "Hide API Key": "ซ่อนคีย์",
        # Translation History
        "Translation History": "ประวัติการแปล",
        "Refresh Records": "รีเฟรช",
        "Back": "ย้อนกลับ",
        "No translation records": "ไม่มีประวัติการแปล",
        "Time": "เวลา",
        "Duration": "ระยะเวลา",
        "Online": "ออนไลน์",
        "Offline": "ออฟไลน์",
        "Open Output Folder": "เปิดโฟลเดอร์เอาต์พุต",
        "Open Log Folder": "เปิดโฟลเดอร์บันทึก",
        "Status": "สถานะ",
        "Success": "สำเร็จ",
        "Failed": "ล้มเหลว",
        "Stopped": "หยุดแล้ว",
        "Tokens": "โทเค็น",
        "Interface Language": "ภาษาของอินเทอร์เฟซ",
        # Bilingual modules
        "Subtitle Bilingual": "เปิดใช้งานคำบรรยายสองภาษา",
        "TXT Bilingual": "เปิดใช้งานโหมดสองภาษา TXT",
        "MD Bilingual": "เปิดใช้งานโหมดสองภาษา Markdown",
        "EPUB Bilingual": "เปิดใช้งานโหมดสองภาษา EPUB",
        "HTML Bilingual": "เปิดใช้งานโหมดสองภาษา HTML",
        # Tab labels
        "Settings": "การตั้งค่า",
        "History": "ประวัติ",
        # Glossary editor
        "Edit Glossary": "แก้ไขอภิธานศัพท์",
        "Load Glossary": "โหลดอภิธานศัพท์",
        "Save Glossary": "บันทึกอภิธานศัพท์",
        # Settings extras
        "AI Glossary Extraction": "การดึงอภิธานศัพท์ด้วย AI",
        "AI Glossary Extraction Info": "ดึงคำศัพท์ด้วย LLM ก่อนการแปล",
        "RPM Limit (0 = unlimited, restart to apply)": "ขีดจำกัด RPM (0 = ไม่จำกัด, รีสตาร์ทเพื่อใช้งาน)",
        "Optional Modules": "โมดูลเสริม",
        # Runtime messages
        "Please select file(s) to translate.": "กรุณาเลือกไฟล์ที่ต้องการแปล",
        "API key is required for online models.": "โมเดลออนไลน์ต้องใช้คีย์ API",
        "Translation stopped by user.": "การแปลถูกหยุดโดยผู้ใช้",
        "No supported files found.": "ไม่พบไฟล์ที่รองรับ",
        "Please select a model first": "กรุณาเลือกโมเดลก่อน",
        "No Local Model Placeholder": "ไม่พบโมเดลในเครื่อง — ติดตั้ง Ollama หรือเปิดใช้งานโมเดลออนไลน์ในการตั้งค่า",
        "Progress Saved Hint": "บันทึกความคืบหน้าแล้ว อัปโหลดไฟล์เดิมอีกครั้งแล้วคลิก 'แปลต่อ' เพื่อดำเนินการต่อ",
        "Unfinished Translation Detected": "ตรวจพบการแปลที่ยังไม่เสร็จ — คุณสามารถคลิก 'แปลต่อ' ได้",
        "API Auth Error": "คีย์ API ไม่ถูกต้องหรือหมดอายุ กรุณาตรวจสอบคีย์ API ที่ด้านบนของแท็บแปล",
        "API Quota Error": "ยอดคงเหลือ/โควตาไม่เพียงพอ กรุณาเติมเงินหรือเปลี่ยนคีย์",
        "API Keys Exhausted": "คีย์ API ทั้งหมดใช้ไม่ได้ (ไม่ถูกต้องหรือโควตาหมด) กรุณาเปลี่ยนคีย์",
        "Completed Files": "เสร็จ {done}/{total}",
        "Missing Segments": "ขาด {count} เซกเมนต์",
        "Segments": "เซกเมนต์",
        # Proofread tab
        "Proofread": "พิสูจน์อักษร",
        "Proofread Document": "เอกสาร",
        "Refresh List": "รีเฟรชรายการ",
        "Save Edits": "บันทึกการแก้ไข",
        "Re-export": "ส่งออกอีกครั้ง",
        "Original Text": "ต้นฉบับ",
        "Translated Text": "คำแปล",
        "Edits saved": "บันทึกการแก้ไข {count} แถวแล้ว",
        "Row count mismatch": "จำนวนแถวไม่ตรงกัน: คาดว่า {expected} ได้ {got} ไม่ได้บันทึกการแก้ไข",
        "No proofread documents": "ไม่พบเอกสารที่พิสูจน์อักษรได้ กรุณาแปลให้เสร็จก่อน (ไม่รองรับ PDF)",
        "Proofread folder missing": "ไม่พบข้อมูลการแปล: {name}",
        "Export completed": "ส่งออกอีกครั้งเสร็จสมบูรณ์",
        "Loaded entries": "โหลด {count} แถวจาก {name} แล้ว"
    },
    # Vietnamese
    "vi": {
        "Source Language": "Ngôn ngữ nguồn",
        "Target Language": "Ngôn ngữ đích",
        "Use Online Model": "Sử dụng mô hình trực tuyến",
        "Models": "Mô hình",
        "API Key": "Khóa API",
        "Remember Key": "Ghi nhớ khóa",
        "Enter your API key here": "Nhập khóa API của bạn tại đây",
        "Upload File": "Tải lên tệp (.docx, .pptx, .xlsx, .pdf)",
        "Upload Files": "Tải lên tệp",
        "Download Translated File": "Tải xuống tệp đã dịch",
        "Status Message": "Thông báo trạng thái",
        "Translate": "Dịch",
        "Local Network Mode (Restart to Apply)": "Chế độ mạng cục bộ (Khởi động lại để áp dụng)",
        "Max Retries": "Số lần thử lại tối đa",
        "Excel Mode": "Bị bỏ sót khi dịch? Thử chế độ 2",
        "Word Bilingual": "Bật so sánh song ngữ",
        "Excel Bilingual": "Bật chế độ song ngữ Excel",
        "PDF Bilingual": "Bật chế độ song ngữ PDF",
        "Continue Translation": "Tiếp tục dịch",
        "Thread Count": "Số lượng luồng",
        "Stop Translation": "Dừng dịch",
        "Stopping": "Đang dừng...",
        "Glossary": "Bảng thuật ngữ",
        "Add Glossary": "+ Thêm bảng thuật ngữ...",
        "Drop CSV file here": "Thả tệp CSV vào đây hoặc nhấp",
        "Add Custom Language": "+ Thêm ngôn ngữ...",
        "New Language Name": "Tên ngôn ngữ mới",
        "Language Name Placeholder": "vd. Klingon",
        "Create Language": "Tạo",
        # Status messages
        "Extracting text": "Đang trích xuất văn bản",
        "Removing duplicates": "Đang xóa bản sao",
        "Splitting text": "Đang chia văn bản",
        "Translating content": "Đang dịch nội dung",
        "Translating": "Đang dịch",
        "Checking results": "Đang kiểm tra kết quả",
        "Restoring structure": "Đang khôi phục cấu trúc",
        "Generating output": "Đang tạo đầu ra",
        "Extracting PDF content": "Đang trích xuất nội dung PDF",
        "Generating translated PDF": "Đang tạo tệp PDF đã dịch",
        "Translation completed": "Dịch hoàn tất",
        "Total tokens used": "Tổng số token đã sử dụng",
        "Preparing content": "Đang chuẩn bị nội dung",
        "Continuing from": "Tiếp tục từ",
        "Retry": "Thử lại",
        "Security Tips": "Mẹo bảo mật",
        "Security Tips Content": "Tính năng này chỉ khả dụng ở chế độ không phải LAN. Khóa API là dữ liệu riêng tư có rủi ro bảo mật. Vui lòng bật một cách cẩn thận.",
        "Show API Key": "Hiện khóa",
        "Hide API Key": "Ẩn khóa",
        # Translation History
        "Translation History": "Lịch sử dịch",
        "Refresh Records": "Làm mới",
        "Back": "Quay lại",
        "No translation records": "Không có lịch sử dịch",
        "Time": "Thời gian",
        "Duration": "Thời lượng",
        "Online": "Trực tuyến",
        "Offline": "Ngoại tuyến",
        "Open Output Folder": "Mở thư mục đầu ra",
        "Open Log Folder": "Mở thư mục nhật ký",
        "Status": "Trạng thái",
        "Success": "Thành công",
        "Failed": "Thất bại",
        "Stopped": "Đã dừng",
        "Tokens": "Token",
        "Interface Language": "Ngôn ngữ giao diện",
        # Bilingual modules
        "Subtitle Bilingual": "Bật phụ đề song ngữ",
        "TXT Bilingual": "Bật chế độ song ngữ TXT",
        "MD Bilingual": "Bật chế độ song ngữ Markdown",
        "EPUB Bilingual": "Bật chế độ song ngữ EPUB",
        "HTML Bilingual": "Bật chế độ song ngữ HTML",
        # Tab labels
        "Settings": "Cài đặt",
        "History": "Lịch sử",
        # Glossary editor
        "Edit Glossary": "Chỉnh sửa bảng thuật ngữ",
        "Load Glossary": "Tải bảng thuật ngữ",
        "Save Glossary": "Lưu bảng thuật ngữ",
        # Settings extras
        "AI Glossary Extraction": "Trích xuất thuật ngữ bằng AI",
        "AI Glossary Extraction Info": "Trích xuất thuật ngữ bằng LLM trước khi dịch",
        "RPM Limit (0 = unlimited, restart to apply)": "Giới hạn RPM (0 = không giới hạn, khởi động lại để áp dụng)",
        "Optional Modules": "Mô-đun tùy chọn",
        # Runtime messages
        "Please select file(s) to translate.": "Vui lòng chọn (các) tệp cần dịch.",
        "API key is required for online models.": "Cần có khóa API cho các mô hình trực tuyến.",
        "Translation stopped by user.": "Người dùng đã dừng dịch.",
        "No supported files found.": "Không tìm thấy tệp được hỗ trợ.",
        "Please select a model first": "Vui lòng chọn mô hình trước.",
        "No Local Model Placeholder": "Không phát hiện mô hình cục bộ — cài đặt Ollama hoặc bật mô hình trực tuyến trong Cài đặt",
        "Progress Saved Hint": "Đã lưu tiến trình. Tải lên lại cùng một tệp và nhấp 'Tiếp tục dịch' để tiếp tục.",
        "Unfinished Translation Detected": "Đã phát hiện bản dịch chưa hoàn tất — bạn có thể nhấp 'Tiếp tục dịch'.",
        "API Auth Error": "Khóa API không hợp lệ hoặc đã hết hạn. Vui lòng kiểm tra Khóa API ở đầu tab Dịch.",
        "API Quota Error": "Số dư/hạn mức không đủ. Vui lòng nạp thêm hoặc đổi khóa khác.",
        "API Keys Exhausted": "Tất cả khóa API đều không dùng được (không hợp lệ hoặc hết hạn mức). Vui lòng thay khóa.",
        "Completed Files": "Hoàn thành {done}/{total}",
        "Missing Segments": "Thiếu {count} đoạn",
        "Segments": "đoạn",
        # Proofread tab
        "Proofread": "Hiệu đính",
        "Proofread Document": "Tài liệu",
        "Refresh List": "Làm mới danh sách",
        "Save Edits": "Lưu chỉnh sửa",
        "Re-export": "Xuất lại",
        "Original Text": "Bản gốc",
        "Translated Text": "Bản dịch",
        "Edits saved": "Đã lưu {count} hàng đã chỉnh sửa.",
        "Row count mismatch": "Số hàng không khớp: cần {expected}, nhận được {got}. Chưa lưu chỉnh sửa.",
        "No proofread documents": "Không tìm thấy tài liệu có thể hiệu đính. Hãy hoàn tất một bản dịch trước (không hỗ trợ PDF).",
        "Proofread folder missing": "Không tìm thấy dữ liệu dịch: {name}",
        "Export completed": "Xuất lại hoàn tất",
        "Loaded entries": "Đã tải {count} hàng từ {name}"
    }
}


# --- Qt desktop app: extra UI labels (Interface Mgmt / Plugins / Progress) ---
# Added without disturbing the literal above; only keys not already present per
# language are merged in. Languages other than en/zh/zh-Hant/ja fall back to en
# via the i18n tr() helper.
_QT_EXTRA_LABELS = {
    "en": {
        "Interface Management": "Interface Management",
        "Plugins": "Plugins",
        "Add Interface": "Add Interface",
        "Active": "Active",
        "Local Model Warning": "Local models translate noticeably worse — quality is not guaranteed.",
        "Output Folder": "Output Folder",
        "Browse": "Browse",
        "Please Configure API Key First": "Please configure your API key first (Settings tab)",
        "Speech-to-Text Model": "Speech-to-Text Model",
        "Translate Subtitles": "Translate subtitles (off = transcribe only)",
        "Image": "Image",
        "Media": "Audio / Video",
        "Unavailable": "Unavailable",
        "Plugin Required": "This format needs a plugin — install it on the Plugins page.",
        "Local Interfaces": "Local Interfaces",
        "Official Interfaces": "Official Interfaces",
        "Custom Interfaces": "Custom Interfaces",
        "Local Interfaces Subtitle": "Ollama / LM Studio models on this machine",
        "Official Interfaces Subtitle": "Built-in provider presets",
        "Custom Interfaces Subtitle": "Interfaces you added",
        "No local models": "No local models found",
        "Set Active": "Set as Active",
        "Edit Params": "Edit Parameters",
        "Delete": "Delete",
        "Interface Name": "Interface Name",
        "Base URL": "Base URL",
        "Model ID": "Model ID",
        "Temperature": "Temperature",
        "Top P": "Top P",
        "Save": "Save",
        "Cancel": "Cancel",
        "Interface saved": "Interface saved",
        "Interface deleted": "Interface deleted",
        "Quick Start": "Quick Start",
        "Advanced": "Advanced",
        "Vocabulary": "Vocabulary",
        "Theme": "Theme",
        # Plugins page
        "Every format is a plugin": "Every format is a plugin",
        "Built-in Formats": "Built-in Formats",
        "Optional Plugins": "Optional Plugins",
        "Built-in": "Built-in",
        "Installed": "Installed",
        "Install": "Install",
        "Installing": "Installing...",
        "Uninstall": "Uninstall",
        "Uninstalling": "Uninstalling...",
        "Working": "Working",
        "Video ffmpeg note": "Video/Audio also requires ffmpeg on your PATH.",
        "Install finished": "Installation finished",
        "Install failed": "Installation failed",
        # Translate page format categories
        "Books": "Books",
        "Documents": "Documents",
        "Subtitles": "Subtitles",
        "Data": "Data",
        "Web": "Web",
        "Complex": "Complex",
        # Progress dashboard
        "Task Progress": "Task Progress",
        "Line Stats": "Line Stats",
        "Elapsed Time": "Elapsed Time",
        "Remaining Time": "Remaining Time",
        "Token Usage": "Token Usage",
        "Live Tasks": "Live Tasks",
        "Average Speed": "Average Speed",
        "Failed Requests": "Failed Requests",
        "Task Stability": "Task Stability",
        "Completed": "Completed",
        "Remaining": "Remaining",
        "lines/min": "lines/min",
    },
    "zh": {
        "Interface Management": "接口管理",
        "Plugins": "插件",
        "Add Interface": "添加接口",
        "Active": "已激活",
        "Local Model Warning": "本地模型翻译质量较差，不保证翻译效果。",
        "Output Folder": "输出文件夹",
        "Browse": "浏览",
        "Please Configure API Key First": "请先配置 API Key（在“设置”中填写）",
        "Speech-to-Text Model": "语音转文字模型",
        "Translate Subtitles": "翻译字幕（不勾选则仅转写）",
        "Image": "图像",
        "Media": "音视频",
        "Unavailable": "不可用",
        "Plugin Required": "该格式需要插件，请在“插件”页面下载。",
        "Local Interfaces": "本地接口",
        "Official Interfaces": "官方接口",
        "Custom Interfaces": "自定义接口",
        "Local Interfaces Subtitle": "本机上的 Ollama / LM Studio 模型",
        "Official Interfaces Subtitle": "内置的服务商预设",
        "Custom Interfaces Subtitle": "您添加的接口",
        "No local models": "未找到本地模型",
        "Set Active": "设为激活",
        "Edit Params": "编辑参数",
        "Delete": "删除",
        "Interface Name": "接口名称",
        "Base URL": "接口地址 (Base URL)",
        "Model ID": "模型 ID",
        "Temperature": "温度 (Temperature)",
        "Top P": "Top P",
        "Save": "保存",
        "Cancel": "取消",
        "Interface saved": "接口已保存",
        "Interface deleted": "接口已删除",
        "Quick Start": "快速开始",
        "Advanced": "高级设置",
        "Vocabulary": "词汇表",
        "Theme": "主题切换",
        "Every format is a plugin": "每一种格式都是一个插件",
        "Built-in Formats": "内置格式",
        "Optional Plugins": "可选插件",
        "Built-in": "已内置",
        "Installed": "已安装",
        "Install": "下载",
        "Installing": "安装中...",
        "Uninstall": "卸载",
        "Uninstalling": "卸载中...",
        "Working": "处理中",
        "Video ffmpeg note": "视频/音频还需要在 PATH 中安装 ffmpeg。",
        "Install finished": "安装完成",
        "Install failed": "安装失败",
        "Books": "书籍",
        "Documents": "文档",
        "Subtitles": "字幕",
        "Data": "数据",
        "Web": "网页",
        "Complex": "复杂",
        "Task Progress": "任务进度",
        "Line Stats": "行数统计",
        "Elapsed Time": "累计时间",
        "Remaining Time": "剩余时间",
        "Token Usage": "累计消耗",
        "Live Tasks": "实时任务数",
        "Average Speed": "平均速度",
        "Failed Requests": "失败请求数",
        "Task Stability": "任务稳定性",
        "Completed": "已完成",
        "Remaining": "剩余",
        "lines/min": "行/分",
    },
    "zh-Hant": {
        "Interface Management": "介面管理",
        "Plugins": "外掛",
        "Add Interface": "新增介面",
        "Active": "已啟用",
        "Local Model Warning": "本地模型翻譯品質較差，不保證翻譯效果。",
        "Output Folder": "輸出資料夾",
        "Browse": "瀏覽",
        "Please Configure API Key First": "請先設定 API Key（在「設定」中填寫）",
        "Speech-to-Text Model": "語音轉文字模型",
        "Translate Subtitles": "翻譯字幕（不勾選則僅轉寫）",
        "Image": "圖像",
        "Media": "音視訊",
        "Unavailable": "不可用",
        "Plugin Required": "此格式需要外掛，請在「外掛」頁面下載。",
        "Local Interfaces": "本機介面",
        "Official Interfaces": "官方介面",
        "Custom Interfaces": "自訂介面",
        "Local Interfaces Subtitle": "本機上的 Ollama / LM Studio 模型",
        "Official Interfaces Subtitle": "內建的服務商預設",
        "Custom Interfaces Subtitle": "您新增的介面",
        "No local models": "未找到本機模型",
        "Set Active": "設為啟用",
        "Edit Params": "編輯參數",
        "Delete": "刪除",
        "Interface Name": "介面名稱",
        "Base URL": "介面位址 (Base URL)",
        "Model ID": "模型 ID",
        "Temperature": "溫度 (Temperature)",
        "Top P": "Top P",
        "Save": "儲存",
        "Cancel": "取消",
        "Interface saved": "介面已儲存",
        "Interface deleted": "介面已刪除",
        "Quick Start": "快速開始",
        "Advanced": "進階設定",
        "Vocabulary": "詞彙表",
        "Theme": "主題切換",
        "Every format is a plugin": "每一種格式都是一個外掛",
        "Built-in Formats": "內建格式",
        "Optional Plugins": "可選外掛",
        "Built-in": "已內建",
        "Installed": "已安裝",
        "Install": "下載",
        "Installing": "安裝中...",
        "Uninstall": "解除安裝",
        "Uninstalling": "解除安裝中...",
        "Working": "處理中",
        "Video ffmpeg note": "影片/音訊還需要在 PATH 中安裝 ffmpeg。",
        "Install finished": "安裝完成",
        "Install failed": "安裝失敗",
        "Books": "書籍",
        "Documents": "文件",
        "Subtitles": "字幕",
        "Data": "資料",
        "Web": "網頁",
        "Complex": "複雜",
        "Task Progress": "任務進度",
        "Line Stats": "行數統計",
        "Elapsed Time": "累計時間",
        "Remaining Time": "剩餘時間",
        "Token Usage": "累計消耗",
        "Live Tasks": "即時任務數",
        "Average Speed": "平均速度",
        "Failed Requests": "失敗請求數",
        "Task Stability": "任務穩定性",
        "Completed": "已完成",
        "Remaining": "剩餘",
        "lines/min": "行/分",
    },
    "ja": {
        "Interface Management": "インターフェース管理",
        "Plugins": "プラグイン",
        "Add Interface": "インターフェース追加",
        "Active": "有効",
        "Local Model Warning": "ローカルモデルは翻訳品質が劣ります。品質は保証されません。",
        "Output Folder": "出力フォルダ",
        "Browse": "参照",
        "Please Configure API Key First": "先に API キーを設定してください（「設定」タブ）",
        "Speech-to-Text Model": "音声認識モデル",
        "Translate Subtitles": "字幕を翻訳（オフ=文字起こしのみ）",
        "Image": "画像",
        "Media": "音声・動画",
        "Unavailable": "利用不可",
        "Plugin Required": "この形式にはプラグインが必要です。プラグインページからインストールしてください。",
        "Local Interfaces": "ローカル接続",
        "Official Interfaces": "公式接続",
        "Custom Interfaces": "カスタム接続",
        "Local Interfaces Subtitle": "このマシンの Ollama / LM Studio モデル",
        "Official Interfaces Subtitle": "組み込みのプロバイダー設定",
        "Custom Interfaces Subtitle": "追加した接続",
        "No local models": "ローカルモデルが見つかりません",
        "Set Active": "有効にする",
        "Edit Params": "パラメータ編集",
        "Delete": "削除",
        "Interface Name": "接続名",
        "Base URL": "接続先 URL (Base URL)",
        "Model ID": "モデル ID",
        "Temperature": "温度 (Temperature)",
        "Top P": "Top P",
        "Save": "保存",
        "Cancel": "キャンセル",
        "Interface saved": "接続を保存しました",
        "Interface deleted": "接続を削除しました",
        "Quick Start": "クイックスタート",
        "Advanced": "詳細設定",
        "Vocabulary": "用語集",
        "Theme": "テーマ切替",
        "Every format is a plugin": "あらゆる形式がプラグイン",
        "Built-in Formats": "組み込み形式",
        "Optional Plugins": "オプションプラグイン",
        "Built-in": "組み込み",
        "Installed": "インストール済み",
        "Install": "ダウンロード",
        "Installing": "インストール中...",
        "Uninstall": "アンインストール",
        "Uninstalling": "アンインストール中...",
        "Working": "処理中",
        "Video ffmpeg note": "動画/音声には PATH 上の ffmpeg も必要です。",
        "Install finished": "インストール完了",
        "Install failed": "インストール失敗",
        "Books": "書籍",
        "Documents": "文書",
        "Subtitles": "字幕",
        "Data": "データ",
        "Web": "ウェブ",
        "Complex": "複雑",
        "Task Progress": "タスク進捗",
        "Line Stats": "行数統計",
        "Elapsed Time": "累計時間",
        "Remaining Time": "残り時間",
        "Token Usage": "累計トークン",
        "Live Tasks": "実行中タスク数",
        "Average Speed": "平均速度",
        "Failed Requests": "失敗リクエスト数",
        "Task Stability": "タスク安定性",
        "Completed": "完了",
        "Remaining": "残り",
        "lines/min": "行/分",
    },
}

for _lang, _labels in _QT_EXTRA_LABELS.items():
    LABEL_TRANSLATIONS.setdefault(_lang, {})
    for _k, _v in _labels.items():
        LABEL_TRANSLATIONS[_lang].setdefault(_k, _v)

# Every key must exist in every language (the i18n completeness test treats the
# English table as the source of truth). Backfill any language that lacks one of
# the new Qt keys with the English string so there are no silent gaps; en/zh/
# zh-Hant/ja already carry proper translations above.
for _lang, _labels in LABEL_TRANSLATIONS.items():
    if _lang == "en":
        continue
    for _k, _v in _QT_EXTRA_LABELS["en"].items():
        _labels.setdefault(_k, _v)